/* Club administration records and eligibility checks. No network or credentials. */
(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./operations-model.js'):root.ClubOperations);if(typeof module==='object'&&module.exports)module.exports=api;else root.ClubAdministration=api;})(typeof window==='object'?window:globalThis,function(M){
'use strict';
const statuses=['open','doing','review','done'],areas=['matchPrep','players','admin','finance','inventory','operations','matchRecords'];
const copy=x=>JSON.parse(JSON.stringify(x));
const defaults=()=>({version:1,tasks:[],registrations:[],checks:[],confirmations:{},activity:[]});
const data=s=>s.administration||defaults();
const season=s=>String(s.meta.season);
const actorValid=a=>a&&typeof a.id==='string'&&a.id.length<=100&&typeof a.name==='string'&&a.name.trim()&&a.name.length<=100;
const stampValid=a=>actorValid(a)&&typeof a.at==='string'&&Number.isFinite(Date.parse(a.at));
function validate(s){
 if(s.administration===undefined)return true;
 const a=s.administration,obj=x=>x&&typeof x==='object'&&!Array.isArray(x),str=(x,max=2000)=>typeof x==='string'&&x.length<=max,fail=()=>{throw Error('행정 업무 기록의 형식을 확인해 주세요.');};
 if(!obj(a)||a.version!==1||!obj(a.confirmations))fail();
 for(const key of ['tasks','registrations','checks','activity']){if(!Array.isArray(a[key])||a[key].length>50000)fail();const ids=new Set();for(const r of a[key]){if(!obj(r)||!str(r.id,100)||!r.id||ids.has(r.id))fail();ids.add(r.id);}}
 for(const r of a.tasks)if(!str(r.title,160)||!r.title.trim()||!str(r.owner,100)||!r.owner.trim()||!statuses.includes(r.status)||!areas.includes(r.area)||!str(r.fixtureId,100)||!str(r.playerId,100)||!str(r.step,100)||!str(r.note)||!str(r.evidence)||!str(r.dueDate,10)||(r.dueDate&&!M.day(r.dueDate))||!stampValid(r.updated)||(r.status==='done'&&(!r.note.trim()&&!r.evidence.trim())))fail();
 const regs=new Set();for(const r of a.registrations){const key=[r.playerId,r.competitionId,r.season].join('|');if(!str(r.playerId,100)||!r.playerId||!str(r.competitionId,100)||!r.competitionId||!str(r.season,30)||!r.season||regs.has(key)||!['pending','confirmed','rejected'].includes(r.status)||!str(r.reference)||!stampValid(r.updated)||(r.status==='confirmed'&&!r.reference.trim()))fail();regs.add(key);}
 const checks=new Set();for(const r of a.checks){const key=r.fixtureId+'|'+r.playerId;if(!str(r.playerId,100)||!r.playerId||!str(r.fixtureId,100)||!r.fixtureId||checks.has(key)||!['unknown','fit','unfit'].includes(r.fitness)||!['unknown','yes','no'].includes(r.participation)||!['unknown','clear','blocked'].includes(r.discipline)||!str(r.reference)||!str(r.context,1000000)||!stampValid(r.updated)||(r.discipline!=='unknown'&&!r.reference.trim()))fail();checks.add(key);}
 for(const [key,r] of Object.entries(a.confirmations))if(!str(key,100)||!stampValid(r.updated)||!str(r.signature,1000000)||!Array.isArray(r.entries)||r.entries.length>100)fail();
 for(const r of a.activity)if(!str(r.kind,100)||!str(r.targetId,100)||!str(r.summary)||!stampValid(r.actor))fail();return true;
}
function change(s,kind,targetId,summary,actor,apply){if(!actorValid(actor))throw Error('작성자 정보를 확인해 주세요.');const next=copy(s),a=next.administration||(next.administration=defaults()),stamp={...actor,at:new Date().toISOString()};apply(a,stamp);a.activity.push({id:typeof crypto==='object'&&crypto.randomUUID?crypto.randomUUID():String(Date.now())+'-'+Math.random(),kind,targetId,summary,actor:stamp});validate(next);return next;}
function upsertTask(s,input,actor){return change(s,'task',input.id,input.title,actor,(a,stamp)=>{if(input.fixtureId&&!s.fixtures.some(f=>f.id===input.fixtureId)||input.playerId&&!s.players.some(p=>p.id===input.playerId))throw Error('연결할 경기와 선수를 확인해 주세요.');const old=a.tasks.find(r=>r.id===input.id),r={...input,step:old?.step||input.step||'',updated:stamp};const i=a.tasks.findIndex(r=>r.id===input.id);if(i<0)a.tasks.push(r);else a.tasks[i]=r;});}
function reviewContext(s,pid,f){const cid=M.competition(s,f),p=s.players.find(p=>p.id===pid),o=M.ensure(s);return JSON.stringify({date:f.date,time:f.kickoffTime||'',competitionId:cid,status:p?.status,availability:p?.availability,rule:o.discipline.rules[cid]||null,opening:o.discipline.opening[cid+'|'+pid]||null,fixtures:s.fixtures.filter(x=>M.competition(s,x)===cid&&M.order(x)<M.order(f)).map(x=>({id:x.id,date:x.date,time:x.kickoffTime,round:x.round,gf:x.gf,ga:x.ga,status:x.scheduleStatus,cards:s.matchLogs.filter(l=>l.fixtureId===x.id&&l.playerId===pid).map(l=>({yellow:l.yellow,red:l.red,status:l.status,minutes:l.minutes}))}))});}
function setReview(s,fid,pid,input,actor){const f=s.fixtures.find(f=>f.id===fid),p=s.players.find(p=>p.id===pid),cid=f&&M.competition(s,f);if(!f||!p||!cid||!s.competitions.some(c=>c.id===cid))throw Error('경기와 소속 대회를 먼저 확인해 주세요.');return change(s,'eligibility',fid+'|'+pid,'등록·참가 확인',actor,(a,stamp)=>{const reg={id:cid+'|'+season(s)+'|'+pid,playerId:pid,competitionId:cid,season:season(s),status:input.registration,reference:input.registrationReference,updated:stamp};const check={id:fid+'|'+pid,fixtureId:fid,playerId:pid,fitness:input.fitness,participation:input.participation,discipline:input.discipline,reference:input.disciplineReference,context:reviewContext(s,pid,f),updated:stamp};for(const [key,r] of [['registrations',reg],['checks',check]]){const i=a[key].findIndex(x=>x.id===r.id);if(i<0)a[key].push(r);else a[key][i]=r;}});}
function eligibility(s,pid,f){const p=s.players.find(p=>p.id===pid),a=data(s),cid=f?M.competition(s,f):'',registration=a.registrations.find(r=>r.playerId===pid&&r.competitionId===cid&&r.season===season(s)),savedCheck=a.checks.find(r=>r.playerId===pid&&r.fixtureId===f?.id),check=savedCheck&&f&&savedCheck.context===reviewContext(s,pid,f)?savedCheck:null,blocked=[],unknown=[];let discipline=null;if(savedCheck&&!check)unknown.push('일정·선수 상태·카드 기록 변경: 재확인 필요');
 if(!p){blocked.push('선수 기록 없음');return {status:'blocked',blocked,unknown,registration,check};}
 if(p.status!=='Active')blocked.push('현역 선수 아님');
 if(!f||!M.day(f.date))unknown.push('경기일 미확인');if(!cid||!s.competitions.some(c=>c.id===cid))unknown.push('대회 미확인');if(['Postponed','Cancelled'].includes(f?.scheduleStatus))blocked.push('연기·취소 경기');
 if(registration?.status==='rejected')blocked.push('대회 등록 미승인');else if(registration?.status!=='confirmed'||!registration.reference.trim())unknown.push('대회·시즌 등록 근거 미확인');
 if(['Injured','Unavailable','International Duty'].includes(p.availability))blocked.push('선수 상태: '+p.availability);
 if(check?.fitness==='unfit')blocked.push('몸 상태 참가 불가');else if(check?.fitness!=='fit')unknown.push('몸 상태 미확인');
 if(check?.participation==='no')blocked.push('참가 불가');else if(check?.participation!=='yes')unknown.push('참가 의사 미확인');
 if(f){discipline=M.discipline(s,pid,f);const rule=M.ensure(s).discipline.rules[cid];if(discipline.manual||discipline.remaining>0)blocked.push(discipline.reason);else if(check?.discipline==='blocked')blocked.push('확인된 출전 정지');else if(!(rule?.enabled&&M.day(f.date)&&f.date>=rule.effectiveDate&&discipline.missingDates===0)&&!(check?.discipline==='clear'&&check.reference.trim()))unknown.push('징계 규정·확인 근거 필요');}
 return {status:blocked.length?'blocked':unknown.length?'review':'ready',blocked,unknown,registration,check,discipline};
}
function fingerprint(s,f,entries){return JSON.stringify({fixture:{id:f.id,date:f.date,time:f.kickoffTime||'',competitionId:M.competition(s,f),status:f.scheduleStatus||'',opponent:f.opponent},season:season(s),entries:entries.map(r=>({...r,eligibility:eligibility(s,r.playerId,f)}))});}
function confirmation(s,f){const r=data(s).confirmations[f.id];if(!r)return {status:'draft'};return {status:r.signature===fingerprint(s,f,s.lineups[f.id]||[])?'confirmed':'stale',record:r};}
function confirm(s,fid,actor){const f=s.fixtures.find(f=>f.id===fid),entries=s.lineups[fid]||[];if(!f||!M.day(f.date)||['Postponed','Cancelled'].includes(f.scheduleStatus))throw Error('경기 일정을 먼저 확인해 주세요.');if(entries.filter(r=>r.role==='Starter').length!==11||entries.filter(r=>r.captain).length!==1||new Set(entries.map(r=>r.playerId)).size!==entries.length)throw Error('선발 11명과 주장 1명을 지정한 뒤 명단을 저장해 주세요.');if(entries.some(r=>eligibility(s,r.playerId,f).status!=='ready'))throw Error('명단 선수의 등록·몸 상태·참가·징계 확인을 완료해 주세요.');return change(s,'confirmation',fid,'경기 명단 최종 확인',actor,(a,stamp)=>{a.confirmations[fid]={entries:copy(entries),signature:fingerprint(s,f,entries),updated:stamp};});}
function seedTasks(s,fid,owner,actor,id){const f=s.fixtures.find(f=>f.id===fid);if(!f||!M.day(f.date))throw Error('경기 날짜를 먼저 입력해 주세요.');const steps=[['schedule','경기 규정·일정 확인',-3,'matchPrep'],['squad','출전 자격·명단 제출',-2,'matchPrep'],['travel','이동·집합 확인',-1,'operations'],['equipment','장비·식수 준비',-1,'inventory'],['result','경기 결과·카드 기록',1,'matchRecords'],['settlement','수당·비용 정산',2,'finance']];return change(s,'preparation',fid,'경기 준비 업무 생성',actor,(a,stamp)=>{for(const [step,title,offset,area] of steps)if(!a.tasks.some(r=>r.fixtureId===fid&&r.step===step))a.tasks.push({id:id+'-'+step,title,owner,dueDate:M.shiftDay(f.date,offset),status:'open',area,fixtureId:fid,playerId:'',step,note:'',evidence:'',updated:stamp});});}
const taskOrder=(rows,today=M.localDay())=>[...rows].sort((a,b)=>Number(a.status==='done')-Number(b.status==='done')||Number(!(a.dueDate&&a.dueDate<today))-Number(!(b.dueDate&&b.dueDate<today))||(a.dueDate||'9999').localeCompare(b.dueDate||'9999')||a.title.localeCompare(b.title));
return {defaults,data,season,validate,upsertTask,setReview,eligibility,confirmation,confirm,seedTasks,taskOrder};
});
