/* Drag, touch and keyboard lineup editor. Uses the existing shared save and membership gates. */
(function(){
'use strict';
const L=window.ClubLineup,A=window.ClubAdministration,M=window.ClubOperations,previousRender=render,previousDraft=lineupDraft,previousValidate=validData,previousSaveStatus=updateSaveStatus;
let selected='',search='',filter='',pickerTarget='',pickerSearch='',history=[],clean='',currentFixture='',gesture=null,suppressClick=0,cachedContext=null,noteSnapshot=false;
const w=(ko,en)=>lang==='en'?en:ko,copy=x=>JSON.parse(JSON.stringify(x)),signature=d=>JSON.stringify(d),editable=()=>!CLOUD_SITE||(memberActive()&&cloud.ready&&!cloud.conflict),requireEdit=()=>{if(!editable())throw Error(w('로그인 및 저장 상태를 확인해 주세요.','Check sign-in and shared save status.'));};
const complete=f=>Number.isFinite(f?.gf)&&Number.isFinite(f?.ga),f=()=>state.fixtures.find(f=>f.id===draftLineup?.fixtureId);
const context=()=>{const match=f();if(cachedContext?.state===state&&cachedContext.fixture===match)return cachedContext.value;const past=complete(match),former=(state.lineups[match?.id]||[]).map(r=>r.playerId),value={players:state.players,allowedFormerIds:past?former:[],blockedIds:past?[]:state.players.filter(p=>A.eligibility(state,p.id,match).status==='blocked').map(p=>p.id)};cachedContext={state,fixture:match,value};return value;};
const names=p=>`<span class="tactics-names"><b>${esc(lang==='en'?p.name:p.koreanName||p.name)}</b>${p.koreanName&&p.name!==p.koreanName?`<small>${esc(lang==='en'?p.koreanName:p.name)}</small>`:''}</span>`;
const avatar=(p,handle=false)=>`<span class="tactics-avatar ${handle?'tactics-handle':''}" aria-hidden="true">${isPhoto(p.photo)&&p.photo?`<img src="${esc(p.photo)}" alt="" draggable="false">`:`<span>${esc(p.number??'—')}</span>`}</span>`;
const mobile=()=>matchMedia('(max-width:760px)').matches;
let pendingLeave=null,allowLeave=false;
const action=(label,type,extra='',kind='')=>`<button type="button" class="btn ${kind}" data-tactics="${type}" ${extra}>${esc(label)}</button>`;
function tacticsModal(...args){modal(...args);document.querySelector('#dialog').classList.add('tactics-dialog');}
function confirmLeave(callback){pendingLeave=callback;tacticsModal(w('저장하지 않은 명단','Unsaved Squad'),`<div class="dialogbody"><p>${esc(w('저장하지 않은 명단 변경이 있습니다. 계속 편집하거나 변경을 버리고 이동할 수 있습니다.','This squad has unsaved changes. Continue editing, or discard the changes and leave.'))}</p></div><div class="dialogfoot">${action(w('계속 편집','Keep Editing'),'leave-keep','','primary')}${action(w('변경 버리고 이동','Discard & Leave'),'leave-discard','','danger')}</div>`);}
function replayNavigation(button){const next=button.cloneNode(false);next.hidden=true;document.body.append(next);next.click();next.remove();}
lineupDraft=function(id){previousDraft(id);const match=state.fixtures.find(x=>x.id===id);draftLineup=L.normalize({...draftLineup,formation:L.formation(match?.formation),note:match?.lineupNote||''},state.players);selected='';history=[];currentFixture=id;clean=signature(draftLineup);};
function ensureDraft(){if(!draftLineup)lineupDraft(M.nextFixture(state)?.id||state.fixtures.find(x=>!complete(x)&&x.scheduleStatus!=='Postponed'&&x.scheduleStatus!=='Cancelled')?.id||[...state.fixtures].sort((a,b)=>M.order(b).localeCompare(M.order(a)))[0]?.id||'');if(currentFixture!==draftLineup.fixtureId||!draftLineup.formation){const match=f();draftLineup=L.normalize({...draftLineup,formation:L.formation(match?.formation),note:match?.lineupNote||''},state.players);currentFixture=draftLineup.fixtureId;clean=signature(draftLineup);history=[];selected='';}}
function apply(next){requireEdit();history.push(copy(draftLineup));if(history.length>20)history.shift();draftLineup=next;render();}
function place(pid,target){requireEdit();const next=L.place(draftLineup,pid,target,context());apply(next);selected=target==='remove'?'':pid;render();announce(w('선수 배치를 변경했습니다. 명단 저장을 눌러 반영하세요.','Placement changed. Save the squad to publish it.'));}
function saveLabel(){if(draftLineup&&signature(draftLineup)!==clean)return w('저장할 변경 있음','Unsaved changes');if(CLOUD_SITE&&(cloud.conflict||cloud.error))return w('공유 저장 확인 필요','Shared save needs attention');if(CLOUD_SITE&&cloud.draft)return w('공유 저장 중…','Saving to club storage…');return w('저장된 명단','Saved squad');}
function announce(text){const el=document.querySelector('#tactics-announcement');if(el)el.textContent=text;}
function status(p){if(complete(f()))return p.status==='Active'?w('과거 경기 기록','Historical record'):w('현재 방출 · 당시 명단','Former player · historical squad');const e=A.eligibility(state,p.id,f());return e.status==='blocked'?w('출전 불가','Unavailable'):e.status==='ready'?w('자격 확인 완료','Verified'):w('자격 확인 필요','Review required');}
function playerCard(p,onPitch=false){const entry=draftLineup.entries.find(r=>r.playerId===p.id),blocked=context().blockedIds.includes(p.id);return `<button type="button" class="tactics-player ${onPitch?'on-pitch':''} ${selected===p.id?'is-selected':''} ${blocked?'is-blocked':''}" data-tactics="select" data-player="${esc(p.id)}" draggable="${blocked||mobile()?'false':'true'}" aria-label="${esc(playerDisplayName(p)+' '+w('선택','select'))}" aria-pressed="${selected===p.id}" ${blocked&&!entry?'disabled':''}>${avatar(p,true)}${names(p)}<span class="tactics-player-meta">${esc(p.number??'—')} · ${esc(p.position)} ${entry?.captain?'· C':''}${onPitch?'':` · ${esc(entry?(entry.role==='Starter'?w('선발','Starter'):w('벤치','Bench')):w('미선택','Not selected'))}`}</span>${onPitch?'':`<small class="tactics-status ${blocked?'danger':''}">${esc(status(p))}</small>`}</button>`;}
function selectionBar(){const p=state.players.find(p=>p.id===selected),entry=draftLineup.entries.find(r=>r.playerId===selected);return `<div class="tactics-selection no-print"><div>${p?names(p):`<strong>${esc(w('자리 선택 → 선수 선택','Select a position → choose a player'))}</strong>`}<small>${esc(p?w('빈자리나 다른 선수 자리를 누르면 배치·교환합니다.','Choose a position to place or swap.'):w('빈 자리를 누르면 선수 목록이 열립니다. 배치된 선수는 눌러 교체·벤치 이동을 할 수 있습니다.','Tap an empty position to choose a player. Tap an assigned player to replace or move them to the bench.'))}</small></div>${p?`<div class="tactics-selection-actions">${entry?.role==='Starter'?action(w(entry.captain?'주장 C':'주장 지정',entry.captain?'Captain C':'Set Captain'),'captain',`data-player="${esc(p.id)}"`,'small'):''}${action(w('벤치로','To Bench'),'bench',`data-player="${esc(p.id)}"`,'small')}${entry?action(w('명단 제외','Remove'),'remove',`data-player="${esc(p.id)}"`,'small danger'):''}${action(w('선택 해제','Deselect'),'deselect','','small light')}</div>`:''}</div>`;}
renderLineup=function(){ensureDraft();const match=f();if(!match)return head('경기 명단','경기 일정을 먼저 등록해 주세요.',btn('경기 일정','nav','calendar','data-view="fixtures"'));const entries=draftLineup.entries,starters=entries.filter(r=>r.role==='Starter'),bench=entries.filter(r=>r.role!=='Starter'),past=complete(match),dirty=signature(draftLineup)!==clean,players=state.players.filter(p=>p.status==='Active'||past&&(state.lineups[match.id]||[]).some(r=>r.playerId===p.id)),pool=players.filter(p=>(!filter||p.position===filter)&&(!search||(p.name+' '+(p.koreanName||'')+' '+p.number).toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>Number(a.number||999)-Number(b.number||999));
return head('출전 명단·전술',w('경기장 자리를 눌러 선수를 고르고, 경기별 명단을 저장합니다.','Tap a pitch position to choose a player and save the squad.'),action(w('최근 명단 불러오기','Load Recent Squad'),'copy','','light')+action(w('명단 인쇄','Print Squad'),'print','','light')+action(w('명단 저장','Save Squad'),'save','','primary'))+
`<div class="panel tactics-controls no-print"><div class="field"><label for="lineup-fixture">${esc(w('경기 선택','Fixture'))}</label><select id="lineup-fixture" aria-label="${esc(w('경기 선택','Fixture'))}">${dynamicChoices('fixture',match.id)}</select></div><div class="field"><label for="tactics-formation">${esc(w('포메이션','Formation'))}</label><select id="tactics-formation">${Object.keys(L.shapes).map(x=>`<option ${x===draftLineup.formation?'selected':''}>${x}</option>`).join('')}</select></div><div class="tactics-save-status ${dirty?'warning':''}">${esc(saveLabel())}</div>${action(w('되돌리기','Undo'),'undo',history.length?'':'disabled','small light')}${action(w('명단 비우기','Clear Squad'),'clear','','small danger')}</div>
<div class="tactics-context"><div><strong>R${esc(match.round)}${match.movedToRound?` (${esc(w(match.movedToRound+'주차 개최','Played in week '+match.movedToRound))})`:""} · ${esc(match.opponent)}</strong><p>${esc(match.date||w('경기일 미확인','Date not recorded'))}${match.kickoffTime?' · '+esc(match.kickoffTime)+' CAT':''} · ${esc(match.venue||w('경기장 미입력','Venue not entered'))}</p></div>${action(w('경기 준비·자격 확인','Preparation & Eligibility'),'prepare','','small light')}</div>
${past?`<p class="notice tactics-reference">${esc(w('경기 당시 명단입니다. 현재 선수 상태와 구분해 기록을 관리합니다.','This is a historical squad. Current player status is shown separately.'))}${match.lineupSource?` <a href="${esc(match.lineupSource)}" target="_blank" rel="noopener">${esc(w('참고 자료','Reference'))}</a>`:''}</p>`:`<p class="notice amber">${esc(w('이 화면은 명단 초안입니다. 저장 후 경기 준비에서 출전 자격과 최종 명단을 확인하세요.','This is a squad draft. Review eligibility and confirm the saved squad in Match Preparation.'))}</p>`}
${selectionBar()}<div id="tactics-announcement" class="sr-only" role="status" aria-live="polite"></div><div class="tactics-workbench"><section class="tactics-pitch-panel"><div class="tactics-pitch-title"><strong>${esc(draftLineup.formation)}</strong><span>${esc(w('선발','Starters'))} ${starters.length}/11 · ${esc(w('벤치','Bench'))} ${bench.length}</span></div><div class="tactics-pitch" data-defenders="${L.shapes[draftLineup.formation][0].length}" aria-label="${esc(w('드래그 라인업 경기장','Drag lineup pitch'))}"><div class="tactics-pitch-lines" aria-hidden="true"><div class="tactics-halfway"></div><div class="tactics-center"></div><div class="tactics-box top"></div><div class="tactics-box bottom"></div><div class="tactics-goal top"></div><div class="tactics-goal bottom"></div></div>${L.slots(draftLineup.formation).map(slot=>{const r=entries.find(r=>r.role==='Starter'&&r.slot===slot.id),p=r&&getPlayer(r.playerId);return `<div class="tactics-slot ${p?'filled':'empty'}" data-tactics-drop="${slot.id}" data-group="${slot.group}" style="left:${slot.x}%;top:${slot.y}%"><span class="tactics-position">${slot.id}</span>${p?playerCard(p,true):`<button type="button" class="tactics-empty" data-tactics="slot" data-slot="${slot.id}" aria-label="${slot.id+' '+esc(w('선수 배치','assign player'))}"><span>+</span><small>${esc(w('배치','Assign'))}</small></button>`}</div>`;}).join('')}</div>
<div class="tactics-bench" data-tactics-drop="bench"><div class="tactics-bench-head"><h2>${esc(w('벤치','Bench'))} <small>${bench.length}</small></h2>${action(w('벤치 선수 추가','Add to Bench'),'add-bench','','small light')}</div><div class="tactics-bench-cards">${bench.map(r=>getPlayer(r.playerId)).filter(Boolean).map(p=>playerCard(p)).join('')||`<p class="tiny">${esc(w('벤치 선수를 추가하세요.','Add players to the bench.'))}</p>`}</div><div class="tactics-note field"><label for="tactics-note">${esc(w('전술 메모','Tactical Note'))}</label><textarea id="tactics-note" maxlength="1000" rows="2" placeholder="${esc(w('팀 지시사항이나 경기 계획을 입력하세요.','Team instructions or match plan.'))}">${esc(draftLineup.note)}</textarea></div></section>
<aside class="panel tactics-pool no-print"><div class="panelhead"><h2>${esc(w('선수 목록','Player List'))}</h2><span class="tiny">${players.length}${esc(w('명',' players'))}</span></div><div class="tactics-pool-filters"><label class="sr-only" for="tactics-search">${esc(w('선수 검색','Find Player'))}</label><input id="tactics-search" type="search" placeholder="${esc(w('이름·등번호 검색','Name or shirt number'))}" value="${esc(search)}"><div role="group" aria-label="${esc(w('포지션 필터','Position Filter'))}">${['','GK','DF','MF','FW'].map(pos=>action(pos||w('전체','All'),'filter',`data-position="${pos}" aria-pressed="${pos===filter}"`,pos===filter?'small primary':'small light')).join('')}</div></div><div class="tactics-pool-cards">${pool.map(p=>playerCard(p)).join('')||`<p class="structure-empty">${esc(w('검색 결과가 없습니다.','No matching players.'))}</p>`}</div><div class="tactics-remove-zone" data-tactics-drop="remove">${esc(w('명단에서 제외하려면 여기로 드래그','Drop here to remove from squad'))}</div></aside></div>
<details class="panel tactics-details"><summary>${esc(w('명단 세부 설정 · 주장·이동·교체 역할','Squad Details · Captain, Travel and Roles'))}</summary><div class="table-scroll"><table><thead><tr>${[w('선수','Player'),w('자리','Position'),w('역할','Role'),w('주장','Captain'),w('이동 확인','Travel Confirmed'),...(past?[w('참고 기록','Reference Notes')]:[]),w('관리','Manage')].map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${entries.map(r=>{const p=getPlayer(r.playerId);return `<tr><td>${p?names(p):esc(r.playerId)}</td><td>${esc(r.slot||'—')}</td><td>${r.role==='Starter'?esc(w('선발','Starter')):`<select data-tactics-role="${esc(r.playerId)}" aria-label="${esc((p?playerDisplayName(p):r.playerId)+' '+w('벤치 역할','bench role'))}"><option value="Sub" ${r.role==='Sub'?'selected':''}>${esc(past?w('교체 출전','Substitute Played'):w('벤치','Bench'))}</option><option value="Unused" ${r.role==='Unused'?'selected':''}>${esc(w('미출전','Unused'))}</option></select>`}</td><td>${r.role==='Starter'?`<input type="checkbox" data-tactics-captain="${esc(r.playerId)}" aria-label="${esc((p?playerDisplayName(p):r.playerId)+' '+w('주장','captain'))}" ${r.captain?'checked':''}>`:r.captain?'C':'—'}</td><td><input type="checkbox" data-tactics-travel="${esc(r.playerId)}" aria-label="${esc((p?playerDisplayName(p):r.playerId)+' '+w('이동 확인','travel confirmed'))}" ${r.travel?'checked':''}></td>${past?`<td class="tactics-source-note">${esc(r.sourceNote||'—')}</td>`:''}<td>${action(w('제외','Remove'),'remove',`data-player="${esc(r.playerId)}"`,'small danger')}</td></tr>`;}).join('')}</tbody></table></div></details>`;};
function pickerRows(){
 const target=L.slots(draftLineup.formation).find(s=>s.id===pickerTarget),past=complete(f()),allowed=context();
 const players=state.players.filter(p=>p.status==='Active'||past&&allowed.allowedFormerIds.includes(p.id)).filter(p=>!pickerSearch||(p.name+' '+(p.koreanName||'')+' '+p.number).toLowerCase().includes(pickerSearch.toLowerCase())).sort((a,b)=>Number(b.position===target?.group)-Number(a.position===target?.group)||Number(a.number||999)-Number(b.number||999));
 return players.map(p=>{const entry=draftLineup.entries.find(r=>r.playerId===p.id),blocked=allowed.blockedIds.includes(p.id);return `<button type="button" class="tactics-pick-player" data-tactics="pick" data-player="${esc(p.id)}" data-slot="${esc(pickerTarget)}" aria-label="${esc(playerDisplayName(p)+' · '+(pickerTarget==='bench'?w('벤치에 추가','add to bench'):pickerTarget+' '+w('배치','assign')))}" ${blocked?'disabled':''}>${avatar(p)}${names(p)}<small>${esc(p.number??'—')} · ${esc(p.position)} · ${esc(entry?.role==='Starter'?entry.slot:entry?w('벤치','Bench'):w('미선택','Not selected'))} · ${esc(status(p))}</small></button>`;}).join('')||`<p>${esc(w('검색 결과가 없습니다.','No matching players.'))}</p>`;
}
function openPicker(target){
 requireEdit();pickerTarget=target;pickerSearch='';selected='';
 tacticsModal(target==='bench'?w('벤치 선수 추가','Add to Bench'):target+' · '+w('선수 선택','Choose Player'),`<div class="dialogbody"><p>${esc(w('선수를 누르면 배치됩니다. 선발 선수끼리는 자리를 교환하며, 새 선수로 교체하면 기존 선수는 벤치로 이동합니다.','Tap a player to assign. Starters swap positions; replacing with a new player moves the current player to the bench.'))}</p><label class="sr-only" for="tactics-picker-search">${esc(w('선수 검색','Find Player'))}</label><input id="tactics-picker-search" class="tactics-picker-search" type="search" placeholder="${esc(w('이름·등번호 검색','Name or shirt number'))}"><div class="tactics-picker-list">${pickerRows()}</div></div>`);
 const title=document.querySelector('#dialog-title');title.tabIndex=-1;title.focus();
}
function playerActions(pid){
 requireEdit();const p=getPlayer(pid),entry=draftLineup.entries.find(r=>r.playerId===pid);if(!p)return;
 if(!entry){openPicker('bench');return;}
 tacticsModal(playerDisplayName(p),`<div class="dialogbody"><p>${esc(entry.role==='Starter'?entry.slot:w('벤치','Bench'))} · ${esc(status(p))}</p><div class="tactics-player-actions">${entry.role==='Starter'?action(w('이 자리 선수 교체','Replace at this position'),'choose-slot',`data-slot="${esc(entry.slot)}"`,'primary')+action(w('벤치로 이동','Move to Bench'),'bench',`data-player="${esc(pid)}"`)+action(w('주장 지정','Set Captain'),'captain',`data-player="${esc(pid)}"`):L.slots(draftLineup.formation).map(s=>action(s.id+' '+w('자리로 이동','position'),'pick',`data-slot="${esc(s.id)}" data-player="${esc(pid)}"`)).join('')}${action(w('명단에서 제외','Remove from Squad'),'remove',`data-player="${esc(pid)}"`,'danger')}</div></div>`);
}
function saveSquad(){requireEdit();L.validateDraft(draftLineup,state.players);const c=context();if(draftLineup.entries.some(r=>c.blockedIds.includes(r.playerId)))throw Error(w('출전 불가 선수를 제외한 뒤 저장해 주세요.','Remove unavailable players before saving.'));const next=copy(state),match=next.fixtures.find(x=>x.id===draftLineup.fixtureId);next.lineups[match.id]=copy(draftLineup.entries);match.formation=draftLineup.formation;match.lineupNote=draftLineup.note;validData(next);state=next;save();clean=signature(draftLineup);render();toast(w('명단 저장을 요청했습니다. 저장 상태를 확인해 주세요.','Squad save requested. Check the shared save status.'));}
function copyDialog(){const match=f(),candidates=state.fixtures.filter(x=>x.id!==match.id&&(state.lineups[x.id]||[]).length).sort((a,b)=>M.order(b).localeCompare(M.order(a)));if(!candidates.length)throw Error(w('불러올 명단이 없습니다.','No saved squad to load.'));tacticsModal('최근 명단 불러오기',`<form id="tactics-copy-form"><div class="dialogbody"><label for="tactics-copy-fixture">${esc(w('불러올 경기 명단','Saved Squad'))}</label><select id="tactics-copy-fixture">${candidates.map(x=>`<option value="${esc(x.id)}">R${esc(x.round)} · ${esc(x.opponent)}</option>`).join('')}</select><p class="smallnote">${esc(w('현재 초안을 바꾸며 되돌리기로 복원할 수 있습니다. 현재 출전 불가 선수는 제외합니다.','Replaces the current draft; Undo restores it. Currently unavailable players are excluded.'))}</p></div><div class="dialogfoot">${btn('취소','close-dialog','close')}<button type="submit" class="btn primary">${esc(w('불러오기','Load'))}</button></div></form>`);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-tactics]');if(!b||b.disabled)return;e.preventDefault();e.stopImmediatePropagation();if(Date.now()<suppressClick)return;const type=b.dataset.tactics,pid=b.dataset.player;try{
 if(type==='pick'){const slot=b.dataset.slot;closeDialog();place(pid,slot);selected='';render();document.querySelector(`[data-tactics-drop="${CSS.escape(slot)}"] button`)?.focus({preventScroll:true});return;}
 if(type==='choose-slot'){openPicker(b.dataset.slot);return;}
 if(type==='add-bench'){openPicker('bench');return;}
 if(type==='select'){const slot=b.closest('[data-tactics-drop]')?.dataset.tacticsDrop;if(mobile()){playerActions(pid);return;}if(selected&&selected!==pid&&slot&&slot!=='bench'){place(selected,slot);return;}selected=selected===pid?'':pid;render();return;}
 if(type==='slot'){if(mobile()||!selected){openPicker(b.dataset.slot);return;}place(selected,b.dataset.slot);return;}
 if(type==='deselect'){selected='';render();return;}if(type==='filter'){filter=b.dataset.position;render();return;}
 if(type==='leave-keep'){pendingLeave=null;closeDialog();return;}
 if(type==='leave-discard'){const callback=pendingLeave;pendingLeave=null;closeDialog();lineupDraft(draftLineup.fixtureId);allowLeave=true;try{callback?.();}finally{allowLeave=false;}return;}
 if(type==='prepare'){if(window.clubLineupDirty()&&!allowLeave){confirmLeave(()=>replayNavigation(b));return;}const id=draftLineup.fixtureId;closeDialog();const link=document.createElement('button');link.dataset.adminAction='prepare';link.dataset.fixture=id;document.body.appendChild(link);link.click();link.remove();return;}
 if(type==='print'){if(signature(draftLineup)!==clean)throw Error(w('변경한 명단을 먼저 저장해 주세요.','Save the changed squad before printing.'));const link=document.createElement('button');link.dataset.adminAction='print-squad';link.dataset.fixture=draftLineup.fixtureId;document.body.appendChild(link);link.click();link.remove();return;}
 requireEdit();if(['captain','bench','remove'].includes(type))closeDialog();if(type==='save')saveSquad();else if(type==='captain')apply(L.setCaptain(draftLineup,pid));else if(type==='bench'||type==='remove')place(pid,type);else if(type==='undo'&&history.length){draftLineup=history.pop();selected='';render();}else if(type==='clear'){apply({...copy(draftLineup),entries:[]});selected='';render();}else if(type==='copy')copyDialog();
 }catch(err){toast(err.message,true);}},true);
document.addEventListener('change',e=>{try{if(e.target.id==='lineup-fixture'&&view==='lineup'){e.stopImmediatePropagation();if(signature(draftLineup)!==clean){const id=e.target.value;e.target.value=draftLineup.fixtureId;confirmLeave(()=>{lineupDraft(id);render();});return;}lineupDraft(e.target.value);render();}else if(e.target.id==='tactics-formation'){requireEdit();apply(L.setFormation(draftLineup,e.target.value,state.players));}else if(e.target.dataset.tacticsCaptain){requireEdit();const pid=e.target.dataset.tacticsCaptain;apply(e.target.checked?L.setCaptain(draftLineup,pid):{...copy(draftLineup),entries:draftLineup.entries.map(r=>({...r,captain:r.playerId===pid?false:r.captain}))});}else if(e.target.dataset.tacticsTravel){requireEdit();apply({...copy(draftLineup),entries:draftLineup.entries.map(r=>({...r,travel:r.playerId===e.target.dataset.tacticsTravel?e.target.checked:r.travel}))});}else if(e.target.dataset.tacticsRole){requireEdit();apply({...copy(draftLineup),entries:draftLineup.entries.map(r=>({...r,role:r.playerId===e.target.dataset.tacticsRole?e.target.value:r.role}))});}else if(e.target.id==='tactics-note'){noteSnapshot=false;}}catch(err){toast(err.message,true);render();}},true);
document.addEventListener('input',e=>{if(e.target.id==='tactics-picker-search'){pickerSearch=e.target.value;document.querySelector('.tactics-picker-list').innerHTML=pickerRows();}});
window.clubLineupDirty=()=>view==='lineup'&&!!draftLineup&&signature(draftLineup)!==clean;
document.addEventListener('click',e=>{const b=e.target.closest('[data-action="nav"]');if(b&&window.clubLineupDirty()&&!allowLeave){e.preventDefault();e.stopImmediatePropagation();confirmLeave(()=>replayNavigation(b));}},true);
window.addEventListener('beforeunload',e=>{if(window.clubLineupDirty()){e.preventDefault();e.returnValue='';}});
function searchInput(el){search=el.value;const cursor=el.selectionStart;render();const next=document.querySelector('#tactics-search');next?.focus();if(next&&cursor!==null)next.setSelectionRange(cursor,cursor);}
document.addEventListener('input',e=>{if(e.target.id==='tactics-search'&&!e.isComposing)searchInput(e.target);if(e.target.id==='tactics-note')try{requireEdit();if(!noteSnapshot){history.push(copy(draftLineup));if(history.length>20)history.shift();noteSnapshot=true;}draftLineup.note=e.target.value;const status=document.querySelector('.tactics-save-status');if(status){status.classList.add('warning');status.textContent=w('저장할 변경 있음','Unsaved changes');}document.querySelector('[data-tactics="undo"]')?.removeAttribute('disabled');}catch(err){e.target.value=draftLineup.note;toast(err.message,true);}});document.addEventListener('compositionend',e=>{if(e.target.id==='tactics-search')searchInput(e.target);});
document.addEventListener('submit',e=>{if(e.target.id!=='tactics-copy-form')return;e.preventDefault();e.stopImmediatePropagation();try{requireEdit();const id=e.target.querySelector('select').value,source=state.fixtures.find(x=>x.id===id),c=context(),entries=copy(state.lineups[id]||[]).filter(r=>state.players.find(p=>p.id===r.playerId)?.status==='Active'&&!c.blockedIds.includes(r.playerId));for(const r of entries){delete r.source;delete r.sourceRound;delete r.sourcePosition;delete r.sourceNote;}const next=L.normalize({fixtureId:draftLineup.fixtureId,formation:L.formation(source.formation),note:source.lineupNote||'',entries},state.players);closeDialog();apply(next);}catch(err){toast(err.message,true);}},true);
document.addEventListener('dragstart',e=>{const card=e.target.closest('.tactics-player');if(!card)return;if(mobile()){e.preventDefault();return;}try{requireEdit();const pid=card.dataset.player;if(context().blockedIds.includes(pid))throw Error(w('출전 불가 선수입니다.','Player is unavailable.'));e.dataTransfer.setData('application/x-club-player',pid);e.dataTransfer.effectAllowed='move';selected=pid;}catch(err){e.preventDefault();toast(err.message,true);}});
document.addEventListener('dragover',e=>{const target=e.target.closest('[data-tactics-drop]');if(target&&e.dataTransfer.types.includes('application/x-club-player')){e.preventDefault();e.dataTransfer.dropEffect='move';}});
document.addEventListener('drop',e=>{const target=e.target.closest('[data-tactics-drop]'),pid=e.dataTransfer.getData('application/x-club-player');if(!target||!pid)return;e.preventDefault();try{place(pid,target.dataset.tacticsDrop);}catch(err){toast(err.message,true);}});
function cancelGesture(){gesture?.ghost?.remove();document.querySelectorAll('.tactics-drop-active').forEach(el=>el.classList.remove('tactics-drop-active'));gesture=null;}
document.addEventListener('pointerdown',e=>{const handle=e.target.closest('.tactics-handle'),card=handle?.closest('.tactics-player');if(!card||card.disabled||e.button!==0||mobile()||e.pointerType==='touch')return;try{requireEdit();if(context().blockedIds.includes(card.dataset.player))throw Error(w('출전 불가 선수입니다.','Player is unavailable.'));e.preventDefault();gesture={pid:card.dataset.player,x:e.clientX,y:e.clientY,card,moved:false,ghost:null};}catch(err){toast(err.message,true);}}, {capture:true,passive:false});
document.addEventListener('pointermove',e=>{if(!gesture)return;const g=gesture;if(!g.moved&&Math.hypot(e.clientX-g.x,e.clientY-g.y)<7)return;e.preventDefault();g.moved=true;if(!g.ghost){g.ghost=g.card.cloneNode(true);g.ghost.className='tactics-drag-ghost';g.ghost.removeAttribute('data-tactics');g.ghost.setAttribute('aria-hidden','true');document.body.appendChild(g.ghost);}g.ghost.style.left=e.clientX+'px';g.ghost.style.top=e.clientY+'px';document.querySelectorAll('.tactics-drop-active').forEach(el=>el.classList.remove('tactics-drop-active'));document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-tactics-drop]')?.classList.add('tactics-drop-active');},{capture:true,passive:false});
document.addEventListener('pointerup',e=>{if(!gesture)return;const g=gesture,target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-tactics-drop]')?.dataset.tacticsDrop;cancelGesture();suppressClick=Date.now()+300;e.preventDefault();try{if(g.moved){if(target)place(g.pid,target);else announce(w('배치를 변경하지 않았습니다.','Placement unchanged.'));}else{selected=selected===g.pid?'':g.pid;render();}}catch(err){toast(err.message,true);}},{capture:true,passive:false});
document.addEventListener('pointercancel',cancelGesture,true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&gesture)cancelGesture();});
validData=function(s){previousValidate(s);L.validate(s);return true;};
updateSaveStatus=function(){previousSaveStatus();const label=document.querySelector('.tactics-save-status');if(label){label.textContent=saveLabel();label.classList.toggle('warning',signature(draftLineup)!==clean||!!(CLOUD_SITE&&(cloud.conflict||cloud.error)));}};
render=function(){cancelGesture();previousRender();};
})();
