/* Immutable private media uploads and a bounded, per-account offline cache. */
const beforeMediaSave=save,beforeMediaSync=syncNow;
function dataBlob(data){const [head,encoded]=data.split(','),bytes=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0));return new Blob([bytes],{type:head.match(/data:([^;]+)/)[1]});}
async function imageThumb(file,maxSize=384){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('10MB 이하의 JPG·PNG·WebP 사진을 선택해 주세요.');const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>80000000)throw Error('사진 크기가 너무 큽니다.');const canvas=document.createElement('canvas'),ratio=Math.min(1,maxSize/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);for(const q of [.78,.65,.5,.35]){const data=canvas.toDataURL('image/webp',q);if(dataBlob(data).size<=51200)return data;}throw Error('사진을 50KB 이하로 줄이지 못했습니다.');}finally{bitmap.close();}}
function queueMedia(path,data){const list=offlineSync.bundle.mediaQueue||(offlineSync.bundle.mediaQueue=[]);if(!list.some(x=>x.path===path))list.push({path,data});}
async function queueReceipt(file){const generation=membership.generation,data=await imageThumb(file,1024);if(generation!==membership.generation)throw Error('ACCOUNT_CHANGED');const path='receipts/'+membership.user.id+'/'+crypto.randomUUID()+'.webp';queueMedia(path,data);await persistSync();return path;}
async function sameBlob(a,b){const x=new Uint8Array(await a.arrayBuffer()),y=new Uint8Array(await b.arrayBuffer());return x.length===y.length&&x.every((v,i)=>v===y[i]);}
save=function(){if(offlineSync.enabled&&offlineSync.connected){for(const p of state.players){const previous=offlineSync.working.players.find(x=>x.id===p.id);if(!p.photo&&previous?.photo&&p.photoPath===previous.photoPath)delete p.photoPath;if(p.photo&&p.photo!==previous?.photo&&(!p.photoPath||p.photoPath===previous?.photoPath)){const path='players/'+p.id+'/'+crypto.randomUUID()+'.webp';queueMedia(path,p.photo);p.photoPath=path;}}}return beforeMediaSave();};
syncNow=async function(){
 if(offlineSync.enabled&&offlineSync.bundle?.mediaQueue?.length){if(offlineSync.mediaBusy||offlineSync.busy)return;const generation=membership.generation,key=syncKey();offlineSync.mediaBusy=true;
  try{await requireSyncSession();await offlineSync.persist;for(const item of [...offlineSync.bundle.mediaQueue]){const blob=dataBlob(item.data);if(blob.size>51200)throw Error('사진 용량이 너무 큽니다.');const {error}=await membership.client.storage.from('club-media').upload(item.path,blob,{contentType:blob.type,upsert:false});if(generation!==membership.generation||syncKey()!==key)throw Error('ACCOUNT_CHANGED');if(error){const {data:existing,error:readError}=await membership.client.storage.from('club-media').download(item.path);if(generation!==membership.generation)throw Error('ACCOUNT_CHANGED');if(readError||!existing||!await sameBlob(existing,blob))throw error;}
   const media=offlineSync.bundle.mediaCache||(offlineSync.bundle.mediaCache=[]);media.push(item);offlineSync.bundle.mediaCache=media.slice(-100);offlineSync.bundle.mediaQueue=offlineSync.bundle.mediaQueue.filter(x=>x.path!==item.path);await persistSync();}
  }catch(e){if(generation!==membership.generation)return;offlineSync.connected=false;offlineSync.error=e.code==='REAUTH_REQUIRED'?e.message:cloudText('사진 전송 대기 · 기기에 보관됨','Photo upload pending · retained on device');offlineSync.attempts=(offlineSync.attempts||0)+1;clearTimeout(offlineSync.timer);offlineSync.timer=setTimeout(()=>{if(document.visibilityState==='visible')syncNow().catch(()=>{});},Math.min(300000,3000*3**Math.min(offlineSync.attempts,5)));updateSaveStatus();return;}finally{if(generation===membership.generation)offlineSync.mediaBusy=false;}
 }
 return beforeMediaSync();
};
async function hydratePhotos(){if(!offlineSync.enabled||offlineSync.photoBusy)return;const generation=membership.generation,key=syncKey(),currentState=state;offlineSync.photoBusy=true;
 try{const cache=offlineSync.bundle.mediaCache||[];for(const p of currentState.players.filter(p=>p.photoPath)){let item=cache.find(x=>x.path===p.photoPath)||offlineSync.bundle.mediaQueue?.find(x=>x.path===p.photoPath);if(!item&&offlineSync.connected){const {data,error}=await membership.client.storage.from('club-media').download(p.photoPath);if(generation!==membership.generation||syncKey()!==key||state!==currentState)return;if(error||!data||data.size>61440)continue;const reader=new FileReader(),encoded=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(data);});if(generation!==membership.generation)return;item={path:p.photoPath,data:encoded};cache.push(item);}if(item){p.photo=item.data;const working=offlineSync.working.players.find(x=>x.id===p.id);if(working)working.photo=item.data;}}
  if(generation===membership.generation){offlineSync.bundle.mediaCache=cache.slice(-100);await persistSync();}
 }finally{if(generation===membership.generation)offlineSync.photoBusy=false;}
}
const beforePhotoWorking=refreshWorking;refreshWorking=function(){beforePhotoWorking();const generation=membership.generation;hydratePhotos().then(()=>{if(generation===membership.generation&&cloud.ready&&!document.querySelector('#dialog[open]'))render();}).catch(()=>{});};

async function openReceipt(id){const t=state.operations.finance.transactions.find(t=>t.id===id);if(!t?.receiptPath)return;const generation=membership.generation,key=syncKey();let image=(offlineSync.bundle.mediaCache||[]).concat(offlineSync.bundle.mediaQueue||[]).find(m=>m.path===t.receiptPath);if(!image){if(!offlineSync.connected)throw Error(cloudText('이 사진은 기기에 보관하지 않았습니다. 연결 후 열어 주세요.','This photo is not on this device. Connect to open it.'));await requireSyncSession();const {data,error}=await membership.client.storage.from('club-media').download(t.receiptPath);if(generation!==membership.generation||syncKey()!==key)throw Error('ACCOUNT_CHANGED');if(error||!data||data.size>61440)throw Error(cloudText('영수증을 불러오지 못했습니다.','Could not load the receipt.'));const reader=new FileReader(),encoded=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(data);});if(generation!==membership.generation)throw Error('ACCOUNT_CHANGED');image={path:t.receiptPath,data:encoded};offlineSync.bundle.mediaCache=[...(offlineSync.bundle.mediaCache||[]),image].slice(-100);await persistSync();}if(!isPhoto(image.data))throw Error('INVALID_RECEIPT');modal(cloudText('영수증 사진','Receipt photo'),'<div class="dialogbody"><p>'+esc(t.date)+' · '+esc(t.description)+'</p><img alt="'+esc(cloudText('영수증','Receipt'))+'" src="'+esc(image.data)+'" style="max-width:100%;max-height:65vh;object-fit:contain"></div>',btn(cloudText('닫기','Close'),'close-dialog','close'));}
