/* Explicit migration/restore controls. Backups never contain the medical tables. */
const beforeAdminRender=render;
render=function(){beforeAdminRender();if(!CLOUD_SITE||!memberAdmin()||!cloud.ready||!offlineSync.serviceAvailable)return;const account=document.querySelector('.account-bar')||document.querySelector('#content');account.insertAdjacentHTML('beforeend',btn(cloudText('자료 이전·복원','Migrate / restore'),'offline-admin','settings'));};
let restoreEnvelope=null,restoreRequestId=null;
function adminOfflineTools(){modal(cloudText('자료 이전·복원','Migration and restore'),`<div class="dialogbody"><p>${offlineSync.enabled?cloudText('새 저장 구조를 사용 중입니다. 백업 복원은 모든 회원의 공유 기록을 교체합니다. 의료 정보와 퇴단 선수 보관함은 일반 복원 대상에서 제외됩니다.','The new storage is active. Restoring a backup replaces shared records for all members. Medical data and departed-player archives are excluded.'):cloudText('모든 입력자의 휴대폰이 연결되어 미전송 0건이고 원정 일정이 없는 기간에 이전하세요. 서버에서 입력을 잠근 뒤 자료를 한 번에 옮깁니다.','Migrate when no trip is underway and every writer has connected with zero pending entries. Server writes are paused before the atomic migration.')}</p>${offlineSync.enabled?'':`<label class="field"><span><input id="cutover-no-trip" type="checkbox"> ${cloudText('원정 중인 사람이 없습니다.','No one is currently away.')}</span></label><label class="field"><span><input id="cutover-no-pending" type="checkbox"> ${cloudText('모든 입력자의 미전송 0건을 확인했습니다.','I checked zero pending entries on every writer’s device.')}</span></label><label class="field"><span><input id="cutover-owner" type="checkbox"> ${cloudText('현재 계정을 의료 보관함 최종 관리자로 지정합니다.','Designate this account as the final medical-archive owner.')}</span></label>`}</div>`,`<div class="dialogfoot">${btn(cloudText('현재 자료 백업','Back up current records'),'backup','download')}${offlineSync.enabled?btn(cloudText('공유 자료 복원','Restore shared records'),'restore','upload')+btn(cloudText('기존 사진 이전','Migrate existing photos'),'offline-migrate-photos','upload'):btn(cloudText('이전 시작','Start migration'),'offline-cutover','upload')}${btn(cloudText('입력 잠금 해제','Release maintenance pause'),'offline-maintenance-off','refresh')}${btn(cloudText('닫기','Close'),'close-dialog','close')}</div>`);}
async function activateOfflineDomains(){
 if(!['cutover-no-trip','cutover-no-pending','cutover-owner'].every(id=>document.getElementById(id)?.checked))throw Error(cloudText('원정·미전송·보관함 관리자 항목을 먼저 확인해 주세요.','Confirm the trip, pending-entry and archive-owner checks first.'));
 if(cloud.draft||cloud.conflict||offlineSync.busy)throw Error(cloudText('이 기기의 미전송 기록을 먼저 해결해 주세요.','Resolve this device’s pending entries first.'));
 if(!confirm(cloudText('현재 자료를 백업하고 서버 입력을 잠근 뒤 새 구조로 이전할까요?','Back up current records, pause server writes and migrate to the new storage?')))return;
 exportBackup();await syncRPC('admin_sync_maintenance',{p_enabled:true});
 const current=await requestRevision();await syncRPC('admin_activate_offline',{p_expected_revision:current,p_archive_owner:membership.user.id});closeDialog();await loadCloud();offlineToast(cloudText('훈련·장부·수당 이전이 완료되었습니다.','Training, ledger and allowances migrated.'));
}
async function convertLegacyDraft(){
 const draft=offlineSync.bundle.oldDraft;if(!draft||draft.domainsConverted)return;
 const result=await syncRPC('inspect_legacy_draft',{p_draft:draft});
 if(result.status==='already_applied'){offlineSync.bundle.legacyDraftArchive.push(draft);offlineSync.bundle.oldDraft=null;await persistSync();await cacheDraft(null);return reviewOffline();}
 if(result.status!=='convertible')throw Error(cloudText('이전 기준과 다른 초안입니다. 원본 백업을 내려받아 항목별로 확인해 주세요.','This draft has a different migration baseline. Back up the original and review its entries.'));
 const before=O.copy(result.baseline),after=O.copy(draft.state);
 for(const s of [before,after]){for(const k of ['transactions','allowances'])for(const row of s.operations.finance[k])if(before.operations.finance[k].some(x=>x.id===row.id))row.version='1';for(const row of s.training){const original=before.training.find(x=>x.id===row.id);if(original){row.version='1';row.sessionId=offlineSync.snapshot.training.find(x=>x.id===row.id)?.sessionId||null;}}}
 const actions=O.diff(O.operational(before),O.operational(after),offlineSync.snapshot.sessions,{schemaVersion:1,syncEpoch:offlineSync.snapshot.syncEpoch,ownerUserId:membership.user.id,clientAt:new Date().toISOString()});
 const otherChanges=!O.equal(O.legacyComparable(before),O.legacyComparable(after));
 offlineSync.bundle.queue=O.enqueue(offlineSync.bundle.queue,actions);offlineSync.bundle.legacyDraftArchive.push(O.copy(draft));offlineSync.bundle.oldDraft=otherChanges?{...draft,domainsConverted:true}:null;
 await persistSync();await cacheDraft(null);refreshWorking();reviewOffline();offlineToast(cloudText(`훈련·장부 변경 ${actions.length}건을 복구했습니다.${otherChanges?' 다른 변경은 원본 백업에서 확인해 주세요.':''}`,`Recovered ${actions.length} training/ledger edits.${otherChanges?' Review other edits in the original backup.':''}`));syncNow().catch(()=>{});
}
const beforeRecoveryReview=reviewOffline;
reviewOffline=function(){beforeRecoveryReview();if(offlineSync.bundle.oldDraft&&!offlineSync.bundle.oldDraft.domainsConverted){document.querySelector('#dialog .dialogfoot')?.insertAdjacentHTML('afterbegin',btn(cloudText('구버전 초안 복구','Recover old draft'),'offline-recover-draft','refresh'));}};
function previewRestore(envelope){
 restoreEnvelope=envelope;restoreRequestId=crypto.randomUUID();const data=envelope.confirmedState||envelope.state||envelope;
 if(envelope.format==='chizumulu-offline-backup-v1'&&envelope.complete===false){modal(cloudText('기기 입력 복구','Recover device entries'),`<div class="dialogbody"><p>${cloudText('이 백업은 원정용 최소 사본입니다. 공유 자료 전체를 교체하지 않고 같은 계정의 미전송 입력만 복구합니다.','This backup contains a minimal field-work copy. Recover pending entries for the same account without replacing all shared records.')}</p></div>`,`<div class="dialogfoot">${btn(cloudText('취소','Cancel'),'close-dialog','close')}${btn(cloudText('기기 입력 복구','Recover device entries'),'offline-restore-queue','upload')}</div>`);return;}
 if(!memberAdmin())throw Error(cloudText('공유 자료 복원은 관리자만 할 수 있습니다.','Only administrators may restore shared records.'));
 validData(data);modal(cloudText('공유 자료 복원 확인','Confirm shared restore'),`<div class="dialogbody"><p>${cloudText(`선수 ${data.players.length}명 · 훈련 ${data.training.length}개. 모든 회원의 공유 기록을 교체합니다. 기존 미전송 입력은 확인 목록으로 보존됩니다. 의료 정보는 교체하지 않습니다.`,`Players: ${data.players.length}; training rows: ${data.training.length}. Replace all shared records. Existing pending entries will be retained for review. Medical information is not replaced.`)}</p><p>${cloudText('모든 입력자가 연결된 원정 없는 기간에 실행하세요.','Run this while every writer is connected and no trip is underway.')}</p></div>`,`<div class="dialogfoot">${btn(cloudText('현재 자료 백업','Back up current records'),'backup','download')}${btn(cloudText('취소','Cancel'),'close-dialog','close')}${btn(cloudText('공유 자료 교체','Replace shared records'),'offline-restore-shared','upload')}</div>`);
}
async function restoreDeviceQueue(envelope){
 if(envelope.source!==clubConfig.supabaseUrl||envelope.ownerUserId!==membership.user.id||!Array.isArray(envelope.queue))throw Error(cloudText('같은 구단·같은 계정의 백업만 복구할 수 있습니다.','Restore a backup from the same club and account.'));
 const queue=O.copy(offlineSync.bundle.queue);
 for(const entry of envelope.queue){if(entry.action?.ownerUserId!==membership.user.id||typeof entry.action.mutationId!=='string'||!['queued','conflict','review'].includes(entry.status))throw Error('INVALID_BACKUP_QUEUE');const existing=queue.find(e=>e.action.mutationId===entry.action.mutationId);if(existing){if(!O.equal(existing.action,entry.action))throw Error('MUTATION_ID_REUSED');continue;}const restored=O.copy(entry);if(restored.action.syncEpoch!==offlineSync.snapshot.syncEpoch){restored.status='review';restored.result={code:'SYNC_EPOCH_CHANGED'};}queue.push(restored);}
 const media=O.copy(offlineSync.bundle.mediaQueue||[]);for(const item of envelope.mediaQueue||[]){if(!/^(receipts|players)\/[A-Za-z0-9_-]+\/[A-Fa-f0-9-]+\.(webp|jpg|png)$/.test(item.path)||!/^data:image\/(webp|jpeg|png);base64,[A-Za-z0-9+/=]+$/.test(item.data)||item.data.length>85000)throw Error('INVALID_BACKUP_MEDIA');const existing=media.find(x=>x.path===item.path);if(existing&&existing.data!==item.data)throw Error('INVALID_BACKUP_MEDIA');if(!existing)media.push(item);}
 offlineSync.bundle.queue=queue;offlineSync.bundle.mediaQueue=media;await persistSync();closeDialog();refreshWorking();render();offlineToast(cloudText('기기 입력을 복구했습니다. 확인 후 동기화해 주세요.','Device entries recovered. Review and sync.'));
}
document.addEventListener('change',e=>{if(!offlineSync.enabled||e.target.id!=='restore-file')return;e.stopImmediatePropagation();const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>20*1024*1024)return offlineToast('20MB 이하의 백업을 선택해 주세요.',true);file.text().then(t=>previewRestore(JSON.parse(t))).catch(err=>offlineToast(err.message,true));},true);
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;if(!['offline-admin','offline-cutover','offline-maintenance-off','offline-recover-draft','offline-restore-shared','offline-restore-queue','offline-archive-access','offline-migrate-photos'].includes(action))return;e.preventDefault();e.stopImmediatePropagation();(async()=>{
 if(action==='offline-migrate-photos'){if(!memberAdmin()||!offlineSync.connected||offlineSync.snapshot.fullState===false||offlineSync.busy||syncCounts().pending)throw Error('연결 후 미전송 기록을 먼저 해결해 주세요.');backupOffline();const generation=membership.generation;for(const p of state.players.filter(p=>p.photo&&!p.photoPath)){const data=await imageThumb(dataBlob(p.photo));if(generation!==membership.generation)throw Error('ACCOUNT_CHANGED');const path='players/'+p.id+'/'+crypto.randomUUID()+'.webp';queueMedia(path,data);p.photo=data;p.photoPath=path;}save();closeDialog();await syncNow();render();return;}
 if(action==='offline-admin')return adminOfflineTools();if(action==='offline-cutover')return activateOfflineDomains();
 if(action==='offline-maintenance-off'){await syncRPC('admin_sync_maintenance',{p_enabled:false});closeDialog();await loadCloud();return;}
 if(action==='offline-recover-draft')return convertLegacyDraft();if(action==='offline-restore-queue')return restoreDeviceQueue(restoreEnvelope);
 if(action==='offline-restore-shared'){const counts=syncCounts();if(!offlineSync.connected||offlineSync.busy||counts.pending||counts.conflicts||counts.review||cloud.draft)throw Error(cloudText('연결하고 이 기기의 미전송·충돌을 해결한 뒤 복원해 주세요.','Connect and resolve this device’s pending/conflicting entries before restoring.'));backupOffline();const full=restoreEnvelope.confirmedState||restoreEnvelope.state||restoreEnvelope;await syncRPC('admin_restore_club',{p_state:full,p_sessions:restoreEnvelope.sessions||[],p_expected_revision:cloud.revision,p_mutation_id:restoreRequestId});closeDialog();await loadCloud();offlineToast(cloudText('공유 자료를 복원했습니다. 다른 기기는 연결 후 확인 목록을 점검해 주세요.','Shared records restored. Other devices should review pending entries after connecting.'));return;}
 if(action==='offline-archive-access'){const members=await syncRPC('list_medical_archive_access');modal(cloudText('보관함 열람 계정','Archive access'),`<div class="dialogbody">${members.map(m=>`<section class="medical-row"><strong>${esc(m.name||m.email)}</strong><p>${esc(m.email)}</p>${m.owner?cloudText('최종 관리자','Final owner'):btn(m.allowed?cloudText('열람 해제','Revoke access'):cloudText('열람 허용','Allow access'),'offline-archive-toggle','users',`data-id="${esc(m.id)}" data-allowed="${m.allowed?'false':'true'}"`)}</section>`).join('')}</div>`,btn(cloudText('닫기','Close'),'close-dialog','close'));}
 })().catch(err=>offlineToast(err.message,true));},true);
document.addEventListener('click',e=>{const b=e.target.closest('[data-action="offline-archive-toggle"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();syncRPC('medical_archive_grant',{p_user_id:b.dataset.id,p_allowed:b.dataset.allowed==='true'}).then(()=>{closeDialog();offlineToast(cloudText('보관함 열람 권한을 변경했습니다.','Archive access updated.'));}).catch(err=>offlineToast(err.message,true));},true);
