/* Mobile field-work UI. Existing detailed screens remain available when connected. */
const beforeOfflineRender=render;
render=function(){beforeOfflineRender();if(!offlineSync.enabled||!cloud.ready)return;const content=document.querySelector('#content');
 document.body.classList.toggle('field-mode',offlineSync.matchday);
 content.insertAdjacentHTML('afterbegin',`<section id="offline-status" class="offline-status" aria-live="polite"><div><strong data-sync-summary></strong><small data-sync-time></small></div><div class="offline-tools">${btn(cloudText('동기화','Sync'),'offline-sync','refresh')}${btn(cloudText('확인할 기록','Review entries'),'offline-review','file')}${btn(cloudText('원정 준비','Prepare trip'),'offline-prepare','download')}${btn(offlineSync.matchday?cloudText('전체 화면','Full view'):cloudText('현장 모드','Field mode'),'offline-mode','users')}</div></section>`);
 if(offlineSync.matchday)content.insertAdjacentHTML('afterbegin',fieldDashboard());updateSaveStatus();markExpenseSuspects();
};
function fieldDashboard(){return `<section class="panel field-dashboard"><h1>${cloudText('오늘 현장 업무','Today in the field')}</h1><p>${cloudText('훈련일과 회차를 확인한 뒤 기록하세요. 휴대폰 시각이 다르면 날짜를 직접 선택할 수 있습니다.','Check the training date and session. Select the date explicitly if the phone clock is wrong.')}</p><div class="field-actions">${btn(cloudText('훈련 출석','Training attendance'),'offline-training','users')}${btn(cloudText('지출 기록','Record expense'),'offline-expense','plus')}${btn(cloudText('경기 기록 (온라인)','Match records (online)'),'offline-match','file')}${btn(cloudText('비상 연락처·알레르기','Emergency contacts and allergies'),'offline-medical','shield')}</div></section>`;}
function sessionPicker(selected=''){return `<select name="sessionId" required>${offlineSync.snapshot.sessions.map(s=>`<option value="${esc(s.id)}" ${s.id===selected?'selected':''}>${esc(s.date)} #${esc(s.sessionNo)} · ${esc(s.name||'훈련')}</option>`).join('')}</select>`;}
function openOfflineTraining(sessionId=''){const sessions=offlineSync.snapshot.sessions,selected=sessions.find(s=>s.id===sessionId)||sessions.filter(s=>s.date===ClubOperations.localDay())[0]||[...sessions].sort((a,b)=>b.date.localeCompare(a.date))[0];
 modal(cloudText('훈련 출석','Training attendance'),`<div class="dialogbody"><p>${cloudText('회차 생성은 연결된 상태에서만 가능합니다. 원정 전에 필요한 회차를 준비해 주세요.','Create sessions while connected. Prepare the sessions before leaving.')}</p><form id="offline-session-select">${sessionPicker(selected?.id||'')}</form>${selected?`<div class="field-attendance">${state.players.filter(p=>p.status==='Active').map(p=>{const r=state.training.find(r=>r.sessionId===selected.id&&r.playerId===p.id);return `<label><strong>${esc(playerDisplayName(p))}</strong><select data-field-attendance data-player="${esc(p.id)}" data-session="${esc(selected.id)}"><option value="">${cloudText('미확인','Unknown')}</option>${['Present','Late','Absent','Excused','Rehab'].map(x=>`<option value="${x}" ${r?.attendance===x?'selected':''}>${esc(t(x))}</option>`).join('')}</select></label>`;}).join('')}</div>`:notice(cloudText('준비된 회차가 없습니다. 인터넷에 연결해 회차를 먼저 만들어 주세요.','No prepared sessions. Connect and create a session first.'))}</div>`,`<div class="dialogfoot">${btn(cloudText('새 회차 (온라인)','New session (online)'),'offline-session-new','plus')}${btn(cloudText('완료','Done'),'offline-dialog-done','check')}</div>`);
}
function openSessionForm(){if(!offlineSync.connected)return offlineToast(cloudText('인터넷에 연결한 뒤 회차를 만들어 주세요.','Connect before creating a session.'),true);modal(cloudText('훈련 회차 만들기','Create training session'),`<form id="offline-session-form"><div class="dialogbody"><div id="form-error" class="formerror"></div><div class="formgrid">${fieldHtml(['date',cloudText('훈련일 (CAT)','Training date (CAT)'),'date'],ClubOperations.localDay(),true)}${fieldHtml(['sessionNo',cloudText('하루 중 회차 번호','Session number'),'number'],1,true)}${fieldHtml(['name',cloudText('장소·훈련 이름','Location and session name'),'text'],'',true)}</div><p>${cloudText('같은 날짜에 다른 선수단이 훈련하면 다른 회차 번호를 사용하세요.','Use a different session number for separate squads on the same date.')}</p></div><div class="dialogfoot">${btn(cloudText('취소','Cancel'),'close-dialog','close')}<button class="btn primary" type="submit">${cloudText('회차 생성','Create session')}</button></div></form>`);}
function openOfflineExpense(){modal(cloudText('원정 지출 기록','Trip expense'),`<form id="offline-expense-form"><div class="dialogbody"><div id="form-error" class="formerror"></div><div class="formgrid">${fieldHtml(['date',cloudText('지출일 (CAT)','Expense date (CAT)'),'date'],ClubOperations.localDay(),true)}${fieldHtml(['amount',cloudText('금액 (MWK)','Amount (MWK)'),'number'],'',true)}${fieldHtml(['category',cloudText('항목','Category'),'text'],'',true)}${fieldHtml(['description',cloudText('내용','Description'),'text'],'',true)}<label class="field">${cloudText('결제 수단','Payment method')}<select name="paymentMethod"><option value="cash">${cloudText('현금','Cash')}</option><option value="airtel">Airtel Money</option><option value="mpamba">TNM Mpamba</option><option value="bank">${cloudText('은행','Bank')}</option><option value="other">${cloudText('기타','Other')}</option></select></label>${fieldHtml(['transactionRef',cloudText('거래번호 (있으면)','Transaction reference (if any)'),'text'],'')}<label class="field">${cloudText('원정','Trip')}<select name="tripId"><option value="">${cloudText('선택 안 함','None')}</option>${state.trips.map(t=>`<option value="${esc(t.id)}">${esc(t.name||t.destination||t.date||t.id)}</option>`).join('')}</select></label><label class="field">${cloudText('영수증 사진 (선택)','Receipt photo (optional)')}<input name="receipt" type="file" accept="image/jpeg,image/png,image/webp" capture="environment"></label></div></div><div class="dialogfoot">${btn(cloudText('취소','Cancel'),'close-dialog','close')}<button class="btn primary" type="submit">${cloudText('기기에 기록','Save on device')}</button></div></form>`);}
function medicalView(){const rows=offlineSync.connected?offlineSync.medical:offlineSync.medicalPinned;return `<div class="dialogbody"><p>${cloudText('미확인은 알레르기가 없다는 뜻이 아닙니다. 원정 준비로 보관한 최소 정보만 오프라인에서 표시됩니다.','Unknown does not mean no allergies. Offline view shows only the minimal information saved during trip preparation.')}</p>${state.players.filter(p=>p.status==='Active').map(p=>{const m=rows.find(m=>m.playerId===p.id),d=m?.data;return `<section class="medical-row"><h3>${esc(playerDisplayName(p))}</h3>${d?`<p>${esc(d.contactName)} · ${esc(d.contactRelationship)} · <a href="tel:${esc(d.contactPhone)}">${esc(d.contactPhone)}</a></p><p>${cloudText('알레르기','Allergies')}: ${esc(d.allergyStatus==='none'?cloudText('없음 (확인됨)','None (confirmed)'):d.allergyStatus==='known'?d.allergyNote:cloudText('미확인','Unknown'))}</p><small>${cloudText('확인','Checked')}: ${esc(d.confirmedAt)} · ${esc(d.source)}</small>`:`<p>${cloudText('등록된 정보가 없거나 이 기기에 보관하지 않았습니다.','No information registered or saved on this device.')}</p>`}${offlineSync.connected?btn(cloudText('등록·수정 (온라인)','Edit (online)'),'offline-medical-edit','edit',`data-id="${esc(p.id)}"`):''}</section>`;}).join('')}</div>`;}
function openMedicalEditor(pid){const m=offlineSync.medical.find(m=>m.playerId===pid),d=m?.data||{},p=state.players.find(p=>p.id===pid);if(!offlineSync.connected||!p)return;modal(cloudText('비상 정보 등록','Emergency information'),`<form id="offline-medical-form" data-player="${esc(pid)}" data-version="${esc(m?.version||'0')}"><div class="dialogbody"><h3>${esc(playerDisplayName(p))}</h3><div id="form-error" class="formerror"></div><div class="formgrid">${[['contactName','비상 연락처 이름','Contact name'],['contactRelationship','관계','Relationship'],['contactPhone','전화번호','Phone number'],['source','정보 출처','Information source']].map(([k,ko,en])=>fieldHtml([k,cloudText(ko,en),'text'],d[k]||'',k==='source')).join('')}<label class="field">${cloudText('알레르기 확인','Allergy status')}<select name="allergyStatus">${[['unknown','미확인','Unknown'],['none','없음 (확인됨)','None (confirmed)'],['known','있음','Known']].map(([v,ko,en])=>`<option value="${v}" ${d.allergyStatus===v?'selected':''}>${cloudText(ko,en)}</option>`).join('')}</select></label>${fieldHtml(['allergyNote',cloudText('알레르기 내용','Allergy note'),'textarea'],d.allergyNote||'')}${fieldHtml(['confirmedAt',cloudText('마지막 확인일','Last confirmed'),'date'],d.confirmedAt||ClubOperations.localDay(),true)}${fieldHtml(['consentAt',cloudText('선수 동의일','Player consent date'),'date'],d.consentAt||ClubOperations.localDay(),true)}<label class="field full"><span><input name="consent" type="checkbox" required ${d.consent?'checked':''}> ${cloudText('선수가 등록 및 승인 회원 열람·원정 보관에 동의했습니다.','Player consented to recording, approved-member access and offline trip storage.')}</span></label></div></div><div class="dialogfoot">${btn(cloudText('취소','Cancel'),'close-dialog','close')}<button type="submit" class="btn primary">${cloudText('온라인 저장','Save online')}</button></div></form>`);}
function backupOffline(){const backup={format:'chizumulu-offline-backup-v1',createdAt:new Date().toISOString(),source:clubConfig.supabaseUrl,ownerUserId:membership.user.id,complete:offlineSync.snapshot.fullState!==false,state:O.copy(state),confirmedState:O.merge(offlineSync.snapshot),sessions:O.copy(offlineSync.snapshot.sessions),syncEpoch:offlineSync.snapshot.syncEpoch,queue:O.copy(offlineSync.bundle.queue),mediaQueue:O.copy(offlineSync.bundle.mediaQueue||[]),oldDraft:offlineSync.bundle.oldDraft||null,legacyDraftArchive:O.copy(offlineSync.bundle.legacyDraftArchive||[])};download(JSON.stringify(backup,null,2),'Chizumulu_Offline_Backup_'+ClubOperations.localDay()+'.json','application/json');}
async function prepareOffline(){if(offlineSync.busy||offlineSync.mediaBusy)throw Error(cloudText('동기화가 끝난 뒤 다시 눌러 주세요.','Wait for synchronization to finish, then retry.'));if(!offlineSync.connected)return offlineToast(cloudText('출발 전 인터넷에 연결해 최신 기록을 확인해 주세요.','Connect before departure to check current records.'),true);await syncNow();const c=syncCounts();if(c.pending||c.conflicts||c.review||cloud.draft||!offlineSync.connected)return offlineToast(cloudText('미전송·충돌·확인 항목을 먼저 해결해 주세요.','Resolve pending, conflicting and review entries first.'),true);
 await loadCloud();offlineSync.medicalPinned=O.medicalForOffline(offlineSync.medical);offlineSync.bundle.medicalPinned=offlineSync.medicalPinned;await persistSync();
 modal(cloudText('원정 준비 완료','Trip prepared'),`<div class="dialogbody"><p>${cloudText('최신 명단·훈련 회차와 비상 연락처·알레르기를 이 기기에 보관했습니다. 출전 명단은 인쇄 메뉴에서 PDF로 저장할 수 있습니다. 앱을 닫기 전에 아래 점검을 마치세요.','Latest squad, training sessions and emergency contacts/allergies are saved on this device. Save the lineup as PDF from Print. Finish these checks before closing the app.')}</p><ul><li>${cloudText('미전송·충돌·확인: 0건','Pending/conflict/review: zero')}</li><li>${cloudText('원정 기간 훈련 회차 확인','Check training sessions for the trip')}</li><li>${cloudText('출전 명단 PDF 저장','Save lineup PDF')}</li><li>${cloudText('한 번 인터넷을 끄고 앱 재실행 확인','Turn internet off and verify the app reopens')}</li></ul></div>`,`<div class="dialogfoot">${btn(cloudText('출전 명단','Lineup'),'offline-lineup','users')}${btn(cloudText('확인','Done'),'close-dialog','check')}</div>`);
}
function reviewOffline(){const entries=offlineSync.bundle.queue.filter(e=>e.status!=='queued');modal(cloudText('확인할 기록','Review entries'),`<div class="dialogbody">${offlineSync.bundle.oldDraft?`<section class="medical-row"><strong>${cloudText('이전 앱의 미전송 초안','Pending draft from an older app')}</strong><p>${cloudText('원본을 보존했습니다. 백업 후 관리자와 이전 기준을 확인해 주세요.','Original retained. Back up and check the migration baseline with an administrator.')}</p></section>`:''}${entries.length?entries.map(e=>`<section class="medical-row"><h3>${esc(e.action.kind)} · ${esc(e.action.target.id)}</h3><p>${esc(e.result?.code||cloudText('같은 항목을 다른 값으로 수정했습니다.','The same field was edited to different values.'))}</p>${e.result?.fields?`<table><thead><tr><th>${cloudText('항목','Field')}</th><th>${cloudText('구단 값','Club value')}</th><th>${cloudText('내 값','My value')}</th></tr></thead><tbody>${Object.entries(e.result.fields).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(String(v.current??''))}</td><td>${esc(String(v.proposed??''))}</td></tr>`).join('')}</tbody></table>`:''}${e.status==='conflict'?btn(cloudText('구단 값 사용','Use club values'),'offline-resolve-server','check',`data-id="${esc(e.action.mutationId)}"`)+btn(cloudText('내 값으로 다시 요청','Resubmit my values'),'offline-resolve-local','edit',`data-id="${esc(e.action.mutationId)}"`):''}${btn(cloudText('백업 후 목록에서 제거','Back up and remove'),'offline-review-remove','close',`data-id="${esc(e.action.mutationId)}"`)}</section>`).join(''):notice(cloudText('충돌·확인 필요 기록이 없습니다.','No conflicts or review entries.'))}</div>`,`<div class="dialogfoot">${btn(cloudText('전체 백업','Back up all'),'offline-backup','download')}${btn(cloudText('닫기','Close'),'offline-dialog-done','close')}</div>`);}
function markExpenseSuspects(){const ids=O.suspects(state.operations.finance.transactions);for(const b of document.querySelectorAll('[data-action="ops-transaction"]'))if(ids.has(b.dataset.id)){const cell=b.closest('tr')?.querySelector('td:nth-child(3)');if(cell&&!cell.querySelector('.expense-suspect'))cell.insertAdjacentHTML('beforeend',`<span class="badge amber expense-suspect">${cloudText('중복 의심 · 확인','Possible duplicate · review')}</span>`);}}
document.addEventListener('change',e=>{if(!offlineSync.enabled)return;if(e.target.matches('#offline-session-select select'))openOfflineTraining(e.target.value);if(e.target.hasAttribute('data-field-attendance')){const el=e.target;if(!el.value)return;const session=offlineSync.snapshot.sessions.find(s=>s.id===el.dataset.session),p=state.players.find(p=>p.id===el.dataset.player);let r=state.training.find(r=>r.sessionId===session.id&&r.playerId===p.id);if(!r){r={id:crypto.randomUUID(),sessionId:session.id,playerId:p.id,date:session.date,type:'기술 훈련',attendance:null,minutes:0,rpe:'',notes:''};state.training.push(r);}r.attendance=el.value;try{save();}catch(err){state=O.copy(offlineSync.working);offlineToast(err.message,true);}}});
document.addEventListener('submit',e=>{if(!offlineSync.enabled||!e.target.id.startsWith('offline-'))return;e.preventDefault();e.stopImmediatePropagation();const form=e.target,fd=new FormData(form),get=k=>String(fd.get(k)||'').trim();(async()=>{
 if(form.id==='offline-session-form'){const action={schemaVersion:1,syncEpoch:offlineSync.snapshot.syncEpoch,ownerUserId:membership.user.id,mutationId:crypto.randomUUID(),kind:'session.create',target:{id:crypto.randomUUID()},patch:{date:get('date'),sessionNo:Number(get('sessionNo')),name:get('name')},clientAt:new Date().toISOString()};const result=(await syncRPC('apply_club_actions',{p_actions:[action]})).results[0];if(result.status!=='applied')throw Error(result.code==='SESSION_EXISTS'?'같은 날짜와 번호의 회차가 있습니다. 기존 회차를 확인해 주세요.':result.code||'회차를 생성하지 못했습니다.');closeDialog();await loadCloud();openOfflineTraining(result.record.id);}
 else if(form.id==='offline-expense-form'){const amount=Number(get('amount'));O.money(amount);if(!ClubOperations.day(get('date'))||!get('category')||!get('description'))throw Error('날짜·항목·내용을 확인해 주세요.');const receipt=fd.get('receipt');let receiptPath='';if(receipt?.size&&typeof queueReceipt==='function')receiptPath=await queueReceipt(receipt);
  state.operations.finance.transactions.push({id:crypto.randomUUID(),date:get('date'),type:'expense',amount,category:get('category'),description:get('description'),tripId:get('tripId'),paymentMethod:get('paymentMethod'),transactionRef:get('transactionRef'),receiptPath,voided:false});save();closeDialog();render();}
 else if(form.id==='offline-medical-form'){const data=Object.fromEntries(['contactName','contactRelationship','contactPhone','allergyStatus','allergyNote','source','confirmedAt','consentAt'].map(k=>[k,get(k)]));data.consent=fd.has('consent');const result=await syncRPC('save_player_medical',{p_player_id:form.dataset.player,p_data:data,p_base_version:form.dataset.version});offlineSync.medical=offlineSync.medical.filter(m=>m.playerId!==result.playerId).concat(result);closeDialog();modal(cloudText('비상 정보','Emergency information'),medicalView(),btn(cloudText('닫기','Close'),'close-dialog','close'));}
 })().catch(err=>formError(err.message));},true);
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||!offlineSync.enabled)return;const a=b.dataset.action;
 if(a==='backup'){e.preventDefault();e.stopImmediatePropagation();return backupOffline();}
 if(!a.startsWith('offline-')||['offline-admin','offline-cutover','offline-maintenance-off','offline-recover-draft','offline-restore-shared','offline-restore-queue','offline-archive-access','offline-archive-toggle','offline-migrate-photos'].includes(a))return;e.preventDefault();e.stopImmediatePropagation();(async()=>{
  if(a==='offline-sync')await syncNow();else if(a==='offline-mode'){offlineSync.matchday=!offlineSync.matchday;render();}
  else if(a==='offline-training')openOfflineTraining();else if(a==='offline-session-new')openSessionForm();else if(a==='offline-expense')openOfflineExpense();
  else if(a==='offline-medical')modal(cloudText('비상 정보','Emergency information'),medicalView(),`<div class="dialogfoot">${offlineSync.connected?btn(cloudText('퇴단 선수 보관함','Departed players archive'),'offline-medical-archive','file'):''}${btn(cloudText('닫기','Close'),'close-dialog','close')}</div>`);
  else if(a==='offline-receipt')await openReceipt(b.dataset.id);
  else if(a==='offline-medical-edit')openMedicalEditor(b.dataset.id);
  else if(a==='offline-medical-archive'){if(!offlineSync.connected)throw Error('보관함은 온라인에서만 열 수 있습니다.');const {data,error}=await membership.client.from('player_medical_archive').select('id,player_id,data,archived_at');if(error)throw error;modal(cloudText('퇴단 선수 보관함','Departed players archive'),`<div class="dialogbody">${data.length?data.map(m=>`<section class="medical-row"><strong>${esc(m.player_id)}</strong><p>${esc(m.data.contactName)} · ${esc(m.data.contactPhone)}</p><p>${esc(m.data.allergyStatus==='known'?m.data.allergyNote:m.data.allergyStatus==='none'?'없음 (확인됨)':'미확인')}</p><small>${esc(m.archived_at)}</small></section>`).join(''):notice(cloudText('열람 권한이 없거나 보관된 정보가 없습니다.','No archive access or no archived information.'))}</div>`,`<div class="dialogfoot">${btn(cloudText('계정 지정','Designate account'),'offline-archive-access','users')}${btn(cloudText('닫기','Close'),'close-dialog','close')}</div>`);}
  else if(a==='offline-archive-access'){const uid=prompt(cloudText('보관함 열람을 허용할 계정의 회원 ID를 입력하세요. 회원 관리에서 ID를 확인할 수 있습니다.','Enter the member ID to authorize archive access.'));if(uid)await syncRPC('medical_archive_grant',{p_user_id:uid,p_allowed:true});}
  else if(a==='offline-prepare')await prepareOffline();else if(a==='offline-review')reviewOffline();else if(a==='offline-backup')backupOffline();
  else if(a==='offline-dialog-done'){closeDialog();refreshWorking();render();}
  else if(a==='offline-lineup'){closeDialog();view='lineup';render();}
  else if(a==='offline-match'){view='fixtures';render();offlineToast(cloudText('첫 버전의 오프라인 입력은 출석과 지출입니다. 경기 기록은 연결 후 입력해 주세요.','Offline entry supports attendance and expenses in this version. Enter match records after connecting.'));}
  else if(a==='offline-logout-keep'){closeDialog();await memberLogout(true);}
  else if(a==='offline-logout-delete'){if(!confirm(cloudText('이 기기의 미전송 입력을 영구 삭제하고 로그아웃할까요? 먼저 백업할 수 있습니다.','Permanently discard pending entries and sign out? You can back up first.')))return;await syncStore('delete');cloud.draft=null;await cacheDraft(null);await memberLogout(true);}
  else if(a.startsWith('offline-resolve-')||a==='offline-review-remove'){const entry=offlineSync.bundle.queue.find(x=>x.action.mutationId===b.dataset.id);if(!entry)return;
   if(a==='offline-review-remove'){backupOffline();if(!confirm(cloudText('백업한 이 기록을 확인 목록에서 제거할까요?','Remove this entry after backing it up?')))return;}
   if(a==='offline-resolve-local'){if(!offlineSync.connected)throw Error('구단의 현재 값을 확인하려면 연결이 필요합니다.');await syncNow();const r=entry.result.current,a2=O.copy(entry.action);a2.mutationId=crypto.randomUUID();a2.baseRecordVersion=entry.result.version;a2.baseRecordExists=true;a2.base=Object.fromEntries(Object.keys(a2.patch).map(k=>[k,r[k]]));offlineSync.bundle.queue.push({action:a2,status:'queued',attempted:false});}
   offlineSync.bundle.queue=offlineSync.bundle.queue.filter(x=>x!==entry);await persistSync();refreshWorking();reviewOffline();syncNow().catch(()=>{});
  }
 })().catch(err=>offlineToast(err.message,true));},true);
// Unsupported offline edits cannot overwrite fields omitted from the offline allow-list.
document.addEventListener('click',e=>{if(!offlineSync.enabled||offlineSync.connected)return;const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;
 if(['new-player','edit-player','apply-restore','undo','new-record','edit-record','confirm-delete','ops-allowance','ops-pay','ops-void-allowance','ops-opening'].includes(a)){e.preventDefault();e.stopImmediatePropagation();offlineToast(cloudText('이 항목은 인터넷 연결 후 수정해 주세요.','Edit this item after connecting.'),true);}},true);
if('serviceWorker' in navigator&&CLOUD_SITE)navigator.serviceWorker.register('sw.js').catch(()=>{});
