/* Shared record calculations. No network, credentials or browser storage. */
(function(root){
  'use strict';
  const copy=x=>JSON.parse(JSON.stringify(x));
  const money=x=>Math.round(Number(x)*100);
  const day=x=>typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)&&Number.isFinite(Date.parse(x))&&new Date(x+'T12:00:00Z').toISOString().slice(0,10)===x;
  const localDay=(now=new Date())=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Africa/Blantyre',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);
  const shiftDay=(date,n)=>new Date(Date.parse(date+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
  function week(date=localDay()){const d=new Date(date+'T12:00:00Z'),start=shiftDay(date,-((d.getUTCDay()+6)%7));return Array.from({length:7},(_,n)=>shiftDay(start,n));}
  function defaults(){return {version:1,finance:{openingBalance:0,transactions:[],allowances:[]},notice:{enabled:false,title:'기상·훈련 공지',body:''},workSchedules:{},attendancePlans:{},trainingDays:[0,2,4],discipline:{rules:{},opening:{}},stockMovements:[],activity:[]};}
  function ensure(s){if(s.operations===undefined)s.operations=defaults();return s.operations;}
  function paid(s,id){return ensure(s).finance.transactions.filter(t=>!t.voided&&t.allowanceId===id).reduce((n,t)=>n+money(t.amount),0)/100;}
  function outstanding(s,a){return a.voided?0:Math.max(0,(money(a.amount)-money(paid(s,a.id)))/100);}
  function finance(s){const f=ensure(s).finance,ts=f.transactions.filter(t=>!t.voided),income=ts.filter(t=>t.type==='income').reduce((n,t)=>n+money(t.amount),0),expense=ts.filter(t=>t.type==='expense').reduce((n,t)=>n+money(t.amount),0);return {income:income/100,expense:expense/100,balance:(money(f.openingBalance)+income-expense)/100,unpaid:f.allowances.reduce((n,a)=>n+money(outstanding(s,a)),0)/100};}
  function payment(s,aId,record){const a=ensure(s).finance.allowances.find(a=>a.id===aId&&!a.voided);if(!a)throw Error('수당 기록을 찾을 수 없습니다.');if(!Number.isSafeInteger(money(record.amount))||money(record.amount)<=0||money(record.amount)>money(outstanding(s,a)))throw Error('지급액은 미지급액 이하의 양수로 입력해 주세요.');if(s.operations.finance.transactions.some(t=>t.id===record.id))throw Error('이미 기록된 지급입니다.');s.operations.finance.transactions.push({...record,type:'expense',category:'선수 수당',allowanceId:aId,description:a.reason,playerId:a.playerId,voided:false});}
  function issued(s,item){return (s.issues||[]).filter(r=>r.itemId===item.id&&!r.returned).reduce((n,r)=>n+Number(r.qty||0),0);}
  function available(s,item){return Number(item.total||0)-Number(item.damaged||0)-Number(item.consumed||0)-issued(s,item);}
  function shortages(s){return (s.equipment||[]).filter(i=>available(s,i)<=Number(i.reorderLevel||0)).map(i=>({item:i,available:available(s,i),buy:Math.max(0,Math.max(Number(i.targetStock||0),Number(i.reorderLevel||0)+1)-available(s,i))}));}
  function adjustStock(s,id,quantity,record){const i=s.equipment.find(i=>i.id===id);if(!i)throw Error('장비 품목을 찾을 수 없습니다.');if(!Number.isInteger(quantity)||quantity===0)throw Error('수량은 0이 아닌 정수로 입력해 주세요.');if(quantity<0&&available(s,i)+quantity<0)throw Error('가용 재고보다 사용 수량이 많습니다.');if(quantity>0)i.total=Number(i.total||0)+quantity;else i.consumed=Number(i.consumed||0)-quantity;ensure(s).stockMovements.push({...record,itemId:id,quantity});}
  function attendance(s,p,date){const rows=(s.training||[]).filter(r=>r.playerId===p.id&&r.date===date);if(rows.length)return {value:rows[rows.length-1].attendance,actual:true,multiple:rows.length>1};const o=ensure(s),key=date+'|'+p.id,n=(new Date(date+'T12:00:00Z').getUTCDay()+6)%7;return {value:o.attendancePlans[key]||((o.workSchedules[p.id]||[]).includes(n)?'busy':'planned'),actual:false,multiple:false};}
  function setAttendance(s,pid,date,value,id){if(!day(date)||!s.players.some(p=>p.id===pid))throw Error('선수와 훈련일을 확인해 주세요.');const o=ensure(s),key=date+'|'+pid,rows=s.training.filter(r=>r.playerId===pid&&r.date===date);if(rows.length>1)throw Error('이 날짜에 훈련 기록이 여러 개입니다. 훈련 출석 화면에서 각각 수정해 주세요.');if(['planned','busy','default'].includes(value)){if(rows.length)throw Error('실제 출석 기록은 훈련 출석 화면에서 수정하거나 삭제해 주세요.');if(value==='default')delete o.attendancePlans[key];else o.attendancePlans[key]=value;return;}if(!['Present','Late','Absent','Excused','Rehab'].includes(value))throw Error('출석 상태를 확인해 주세요.');if(date>localDay())throw Error('미래 날짜에는 실제 출석을 기록할 수 없습니다.');if(rows.length)rows[0].attendance=value;else s.training.push({id,playerId:pid,date,type:'기술 훈련',attendance:value,minutes:0,rpe:'',notes:'주간 출석부에서 기록'});delete o.attendancePlans[key];}
  function competition(s,f){if(f.competitionId)return f.competitionId;const name=String(f.competition||'').split(' / ')[0];return s.competitions.find(c=>c.name===name||c.koreanName===name)?.id||'';}
  const played=f=>!['Postponed','Cancelled'].includes(f.scheduleStatus)&&f.gf!==''&&f.gf!=null&&f.ga!==''&&f.ga!=null;
  const order=f=>[f.date||'',f.kickoffTime||'00:00',String(Number(f.round||0)).padStart(5,'0'),f.id].join('|');
  function discipline(s,pid,target){const player=s.players.find(p=>p.id===pid),o=ensure(s),cid=target?competition(s,target):'',rule=o.discipline.rules[cid],r={yellow:0,red:0,remaining:0,manual:player?.availability==='Suspended',enabled:!!rule?.enabled,missingDates:0,violations:[],reason:''};if(!target||!rule?.enabled){r.reason=r.manual?'선수 가용 상태: 징계':'대회 규정 미설정';return r;}if(!day(target.date)||target.date<rule.effectiveDate){r.reason='경기 날짜와 규정 적용 시작일을 확인해 주세요.';return r;}const opening=o.discipline.opening[cid+'|'+pid]||{};r.yellow=Number(opening.yellow||0);r.remaining=Number(opening.remaining||0);const all=s.fixtures.filter(f=>competition(s,f)===cid&&played(f));r.missingDates=all.filter(f=>!day(f.date)).length;const fixtures=all.filter(f=>day(f.date)&&f.date>=rule.effectiveDate&&order(f)<order(target)).sort((a,b)=>order(a).localeCompare(order(b)));for(const f of fixtures){const logs=s.matchLogs.filter(l=>l.fixtureId===f.id&&l.playerId===pid),appearance=logs.some(l=>['Starter','Sub'].includes(l.status)||Number(l.minutes)>0);if(r.remaining>0){if(appearance)r.violations.push(f.id);else r.remaining--;}const yellow=logs.reduce((n,l)=>n+Number(l.yellow||0),0),red=logs.reduce((n,l)=>n+Number(l.red||0),0);r.red+=red;const counted=rule.excludeSecondYellow&&red>0&&yellow>=2?Math.max(0,yellow-2):yellow;r.yellow+=counted;const bans=Math.floor(r.yellow/rule.yellowThreshold);r.yellow%=rule.yellowThreshold;r.remaining+=bans*rule.yellowBan+red*rule.redBan;}r.reason=r.remaining>0?'같은 대회 '+r.remaining+'경기 정지':r.manual?'선수 가용 상태: 징계':'출전 정지 없음';return r;}
  function nextFixture(s){return s.fixtures.filter(f=>day(f.date)&&f.date>=localDay()&&!played(f)&&f.scheduleStatus!=='Postponed'&&f.scheduleStatus!=='Cancelled').sort((a,b)=>order(a).localeCompare(order(b)))[0]||null;}
  function validate(s){if(s.operations===undefined)return true;const o=s.operations,object=x=>x&&typeof x==='object'&&!Array.isArray(x),numeric=(x,integer=false,min=0)=>typeof x==='number'&&Number.isFinite(x)&&Math.abs(x)<1e12&&x>=min&&(!integer||Number.isInteger(x)),text=x=>typeof x==='string'&&x.length<=10000;const fail=()=>{throw Error('구단 운영 기록의 형식을 확인해 주세요.');};if(!object(o)||o.version!==1||!object(o.finance)||!object(o.notice)||!object(o.workSchedules)||!object(o.attendancePlans)||!object(o.discipline)||!object(o.discipline.rules)||!object(o.discipline.opening)||!numeric(o.finance.openingBalance,false,-1e12)||typeof o.notice.enabled!=='boolean'||!text(o.notice.title)||!text(o.notice.body))fail();const ids=new Set();for(const key of ['transactions','allowances']){if(!Array.isArray(o.finance[key])||o.finance[key].length>50000)fail();for(const r of o.finance[key]){if(!object(r)||!text(r.id)||!r.id||ids.has(key+'|'+r.id)||!day(r.date)||!numeric(r.amount)||money(r.amount)<=0||Math.abs(r.amount-money(r.amount)/100)>1e-8||typeof r.voided!=='boolean')fail();ids.add(key+'|'+r.id);if(key==='transactions'&&(!['income','expense'].includes(r.type)||!text(r.category)||!text(r.description)))fail();if(key==='allowances'&&(!text(r.playerId)||!text(r.reason)))fail();}}for(const t of o.finance.transactions)if(t.allowanceId){const a=o.finance.allowances.find(a=>a.id===t.allowanceId);if(!a||t.type!=='expense'||(!t.voided&&a.voided))fail();}for(const a of o.finance.allowances)if(paid(s,a.id)>a.amount+1e-8)fail();const days=x=>Array.isArray(x)&&x.length<=7&&new Set(x).size===x.length&&x.every(n=>Number.isInteger(n)&&n>=0&&n<=6);if(!days(o.trainingDays)||Object.values(o.workSchedules).some(x=>!days(x))||Object.entries(o.attendancePlans).some(([k,v])=>!day(k.split('|')[0])||!['busy','planned'].includes(v)))fail();for(const r of Object.values(o.discipline.rules))if(!object(r)||typeof r.enabled!=='boolean'||!day(r.effectiveDate)||!numeric(r.yellowThreshold,true,1)||!numeric(r.yellowBan,true,1)||!numeric(r.redBan,true,1)||typeof r.excludeSecondYellow!=='boolean'||!text(r.source)||r.yellowThreshold>20||r.yellowBan>20||r.redBan>20)fail();for(const r of Object.values(o.discipline.opening))if(!object(r)||!numeric(r.yellow,true)||!numeric(r.remaining,true))fail();for(const key of ['stockMovements','activity'])if(!Array.isArray(o[key])||o[key].length>50000||o[key].some(r=>!object(r)||!text(r.id)||!text(r.at)))fail();for(const i of s.equipment)for(const k of ['consumed','targetStock'])if(i[k]!==undefined&&i[k]!==''&&i[k]!==null&&!numeric(i[k],true))fail();for(const p of s.players)if(p.dayJob!==undefined&&!text(p.dayJob))fail();return true;}
  const api={copy,money,day,localDay,shiftDay,week,defaults,ensure,paid,outstanding,finance,payment,issued,available,shortages,adjustStock,attendance,setAttendance,competition,played,order,discipline,nextFixture,validate};
  if(typeof module==='object'&&module.exports)module.exports=api;else root.ClubOperations=api;
})(typeof window==='object'?window:globalThis);
