/* Operational screens use the existing approved-member shared save system. */
var operationsViews={};
(function(){
  'use strict';
  const M=window.ClubOperations,days=['월','화','수','목','금','토','일'];
  let weekStart=M.week()[0],disciplineFixture='',weatherData=null,weatherBusy=false,weatherError='',weatherAttempt=0;
  const weatherKey='chizumulu-weather-v1';
  const o=()=>M.ensure(state),money=n=>new Intl.NumberFormat('en-GB',{maximumFractionDigits:2}).format(n),activePlayers=()=>state.players.filter(p=>p.status==='Active');
  const tag=(label,kind='blue')=>`<span class="badge ${kind}">${esc(label)}</span>`;
  const action=(label,name,id='',kind='')=>btn(label,'ops-'+name,'plus',`data-id="${esc(id)}"`,kind);
  const stamp=()=>({id:crypto.randomUUID(),at:new Date().toISOString(),actor:typeof membership!=='undefined'?membership.user?.id||'':'',actorName:typeof membership!=='undefined'?membership.member?.display_name||membership.user?.email||'회원':'회원'});
  const table=(columns,rows,empty='등록된 기록이 없습니다.')=>simpleTable(columns,rows,empty,'위의 추가 버튼으로 기록을 등록해 주세요.');
  const field=(name,label,type='text',value='',extra='')=>`<div class="field"><label for="ops-${name}">${esc(label)}</label><input id="ops-${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`;
  const select=(name,label,options)=>`<div class="field"><label for="ops-${name}">${esc(label)}</label><select id="ops-${name}" name="${name}">${options}</select></div>`;
  const options=(list,current)=>list.map(([value,label])=>`<option value="${esc(value)}" ${String(current)===String(value)?'selected':''}>${esc(label)}</option>`).join('');
  const playerOptions=current=>options(activePlayers().map(p=>[p.id,p.name]),current);
  const fixtureOptions=(current,blank=true)=>options([...(blank?[['','경기 연결 없음']]:[]),...state.fixtures.map(f=>[f.id,`${f.date||'날짜 미정'} · R${f.round||'—'} ${f.opponent}`])],current);
  const daysField=(name,selected)=>`<div class="field"><label>${name==='trainingDays'?'정규 훈련 요일':'본업 때문에 참석이 어려운 요일'}</label><div class="job-day-grid">${days.map((d,n)=>`<label><input type="checkbox" name="${name}" value="${n}" ${selected.includes(n)?'checked':''}>${d}</label>`).join('')}</div></div>`;
  function canEdit(){if(!CLOUD_SITE)return true;return typeof memberActive==='function'&&memberActive()&&cloud.ready&&!cloud.conflict;}
  function change(message,fn){if(!canEdit())throw Error('로그인 및 저장 상태를 확인해 주세요.');const before=clone(state);try{fn();M.validate(state);o().activity.unshift({...stamp(),message});o().activity=o().activity.slice(0,1000);save();}catch(e){state=before;throw e;}render();toast(message);}
  function editor(title,type,body,id=''){modal(title,`<form id="ops-form" data-type="${type}" data-id="${esc(id)}"><div class="dialogbody"><div class="formerror" id="form-error" role="alert"></div><div class="formgrid">${body}</div></div><div class="dialogfoot">${btn('취소','close-dialog','close')}<button class="btn primary" type="submit">${icon('save')}기록 저장</button></div></form>`);}
  function financeSummary(){const f=M.finance(state);return `<div class="summary">${statCard('현재 잔액',money(f.balance),'MWK','기초 잔액 + 수입 − 지출','chart',f.balance<0?'danger':'')}${statCard('누적 수입',money(f.income),'MWK','입장료 · 후원금','chart')}${statCard('누적 지출',money(f.expense),'MWK','교통 · 식수 · 수당 지급','chart')}${statCard('미지급 수당',money(f.unpaid),'MWK','아직 지급하지 않은 금액','info',f.unpaid?'warning':'')}</div>`;}
  function weatherPanel(){const w=weatherData,stale=!w||Date.now()-w.fetchedAt>3600000||!!weatherError,v=n=>Number.isFinite(n)?n:'—',direction=w&&Number.isFinite(w.direction)?daysDirection(w.direction):'—';return `<section class="panel weather-panel"><div class="panelhead"><h2>${icon('calendar')} 치주물루 호수 기상</h2><span class="weather-source">${weatherBusy?'예보 불러오는 중':w?esc(w.time)+' CAT · '+(stale?'오래된 예보 / 연결 확인':'최근 예보'):'아직 예보 없음'} ${action('새로고침','weather-refresh')}</span></div><div class="weather-grid"><div class="weather-metric"><span>풍속 · 풍향</span><b>${v(w?.wind)}<small>m/s · ${esc(direction)}</small></b></div><div class="weather-metric"><span>돌풍</span><b>${v(w?.gust)}<small>m/s</small></b></div><div class="weather-metric"><span>오늘 최대 강수 확률</span><b>${v(w?.rain)}<small>%</small></b></div><div class="weather-metric"><span>호수 파도 높이</span><b class="wave-unavailable">미제공</b></div></div><div class="weather-note">${w&&w.direction>=90&&w.direction<=180?tag('남동풍 예보 · Mwera 및 배편 상황 확인','warning')+' ':''}${stale?'최신 자료를 확인할 수 없으면 최근 받은 예보를 표시합니다. ':''}호수 파도는 제공 자료가 없어 수치를 표시하지 않습니다. 남동풍 여부와 배편 운항은 현지에서 확인해 주세요. <a href="https://open-meteo.com/" target="_blank" rel="noopener noreferrer">예보: Open-Meteo</a> · 말라위 시간(CAT)</div></section>`;}
  function daysDirection(deg){return ['북','북동','동','남동','남','남서','서','북서'][Math.round(deg/45)%8];}
  function noticePanel(){const n=o().notice;return `<div class="notice-bar ${n.enabled?'':'off'}"><div><strong>${esc(n.enabled?n.title:'훈련 공지 꺼짐')}</strong><p>${esc(n.enabled?n.body:'기상 악화, 장소 변경 등의 공지를 직접 표시할 수 있습니다.')}</p></div><div class="notice-actions">${action('공지 수정','notice')}<label class="switch"><input type="checkbox" data-ops-notice ${n.enabled?'checked':''}>공지 표시</label></div></div>`;}
  function dashboard(){const f=M.finance(state),short=M.shortages(state),next=M.nextFixture(state),banned=next?activePlayers().filter(p=>{const d=M.discipline(state,p.id,next);return d.manual||d.remaining>0;}).length:0;return head('구단 대시보드','재정과 선수 가용 인원, 장비·기상 현황을 한눈에 확인합니다.')+weatherPanel()+noticePanel()+`<div class="section-gap">${financeSummary()}</div><div class="dashboard-links">${[['finance','chart','수입·지출 장부',money(f.unpaid)+' MWK 미지급','warning'],['inventory','box','장비·의무 물자',short.length+'종 구매 필요','danger'],['attendance','training','본업·주간 출석',activePlayers().length+'명 일정 관리','blue'],['discipline','shield','카드·출전 정지',next?banned+'명 다음 경기 출전 제한':'다음 경기 날짜 확인 필요','danger'],['weather','calendar','기상·훈련 공지',o().notice.enabled?'공지 표시 중':'공지 꺼짐','blue']].map(([id,ic,title,text,kind])=>`<button class="feature-card" data-action="nav" data-view="${id}">${icon(ic)}<h3>${title}</h3>${tag(text,kind)}</button>`).join('')}<div class="feature-card"><div class="eyebrow">RECENT ACTIVITY</div><h3>최근 입력</h3>${o().activity.slice(0,3).map(r=>`<p>${esc(r.message)}<span class="subtext">${esc(r.actorName)} · ${esc(new Date(r.at).toLocaleString('ko-KR',{timeZone:'Africa/Blantyre'}))} CAT</span></p>`).join('')||'<p>입력한 운영 기록이 여기에 표시됩니다.</p>'}</div></div>`;}
  function financeView(){const f=o().finance;return head('수입·지출 장부','실제 수당 지급액은 장부 지출에 함께 기록됩니다.',action('기초 잔액','opening')+action('수당 등록','allowance','','primary')+action('장부 기록 추가','transaction','','primary'))+financeSummary()+`<section class="panel"><div class="panelhead"><h2>선수별 미지급 수당</h2><span class="tiny">부분 지급 가능 · MWK</span></div>${table(['선수','발생일·사유','발생액','지급액','미지급액','관리'],f.allowances.filter(a=>!a.voided).map(a=>`<tr><td><b>${esc(playerName(a.playerId))}</b></td><td>${esc(a.date)}<span class="subtext">${esc(a.reason)}</span></td><td class="money">${money(a.amount)}</td><td class="money">${money(M.paid(state,a.id))}</td><td>${tag(money(M.outstanding(state,a))+' MWK',M.outstanding(state,a)?'warning':'green')}</td><td class="row-buttons">${M.outstanding(state,a)?action('지급 기록','pay',a.id):''}${action('수정','allowance',a.id)}${!M.paid(state,a.id)?action('취소','void-allowance',a.id):''}</td></tr>`))}</section><section class="panel section-gap"><div class="panelhead"><h2>수입·지출 내역</h2><span class="tiny">기초 잔액 ${money(f.openingBalance)} MWK · 취소 기록 보관</span></div>${table(['날짜','구분','항목·내용','금액 (MWK)','관리'],[...f.transactions].sort((a,b)=>b.date.localeCompare(a.date)).map(t=>`<tr class="${t.voided?'ops-voided':''}"><td>${esc(t.date)}</td><td>${tag(t.voided?'취소':t.type==='income'?'수입':'지출',t.voided?'muted':t.type==='income'?'green':'blue')}</td><td><b>${esc(t.category)}</b><span class="subtext">${esc(t.description)}${t.playerId?' · '+esc(playerName(t.playerId)):''}</span></td><td class="money ${t.type==='income'?'cash-in':'cash-out'}">${t.type==='income'?'+':'−'}${money(t.amount)}</td><td>${!t.voided?(!t.allowanceId?action('수정','transaction',t.id):'')+action('취소','void-transaction',t.id):'—'}</td></tr>`))}</section>`;}
  function inventoryView(){const short=M.shortages(state);return head('장비·의무 물자','사이즈별 축구화와 공, 조끼, 의무 물자를 관리합니다.',action('지급·반납 관리','issues')+btn('품목 추가','new-record','plus','data-type="equipment"','primary'))+`<div class="summary">${statCard('등록 품목',state.equipment.length,'종','사이즈·규격별로 구분','box')}${statCard('구매 필요',short.length,'종','가용 재고가 기준 이하','box','danger')}${statCard('재고 없음',state.equipment.filter(i=>M.available(state,i)<=0).length,'종','지급중·파손·사용분 제외','info','danger')}${statCard('의무 물자',state.equipment.filter(i=>i.category==='의료 용품').length,'종','붕대 · 구급상자 등','shield')}</div><div class="twocol"><section class="panel"><div class="panelhead"><h2>장비 창고 현황</h2><span class="tiny">입고 / 사용은 이력에 남습니다.</span></div>${table(['품목·규격','가용 재고','최소 / 목표','상태','관리'],state.equipment.map(i=>{const n=M.available(state,i),low=n<=i.reorderLevel;return `<tr class="${low?'stock-low':''}"><td><b>${esc(i.name)}</b><span class="subtext">${esc(i.spec)} · ${esc(i.category)}</span><span class="subtext">지급중 ${M.issued(state,i)} · 파손 ${i.damaged||0} · 사용 ${i.consumed||0}</span></td><td class="money ${low?'danger-text':''}">${n} ${esc(i.unit||'개')}</td><td>${i.reorderLevel||0} / ${Math.max(i.targetStock||0,(i.reorderLevel||0)+1)}</td><td>${tag(n<=0?'재고 없음':low?'구매 필요':'보유',low?'danger':'green')}</td><td class="row-buttons">${action('입고·사용','stock',i.id)}${btn('수정','edit-record','edit',`data-type="equipment" data-id="${esc(i.id)}"`)}</td></tr>`;}))}</section><section class="panel shopping-list"><div class="panelhead"><h2>Nkhata Bay 쇼핑 리스트</h2>${tag('자동 계산')}</div><div class="panelbody">${short.map(({item:i,available:n,buy})=>`<div class="checkrow"><span><strong>${esc(i.name)} · ${esc(i.spec||'규격 미입력')}</strong><small>현재 ${n} / 목표 ${Math.max(i.targetStock||0,(i.reorderLevel||0)+1)} ${esc(i.unit||'개')}</small></span><b>${buy} ${esc(i.unit||'개')}</b></div>`).join('')||'<p class="empty-list">현재 구매가 필요한 품목이 없습니다.</p>'}<p class="smallnote">입고 후 최소 기준을 넘으면 목록에서 자동으로 빠집니다.</p></div></section></div><section class="panel section-gap"><div class="panelhead"><h2>최근 입고·사용 이력</h2></div>${table(['시간 (CAT)','품목','수량','사유·입력자'],[...o().stockMovements].reverse().slice(0,30).map(r=>`<tr><td>${esc(new Date(r.at).toLocaleString('ko-KR',{timeZone:'Africa/Blantyre'}))}</td><td>${esc(state.equipment.find(i=>i.id===r.itemId)?.name||'삭제된 품목')}</td><td>${r.quantity>0?'+':''}${r.quantity}</td><td>${esc(r.reason)} · ${esc(r.actorName)}</td></tr>`))}</section>`;}
  const attendanceNames={planned:'참가 예정',busy:'본업 일정',default:'기본 일정 적용',Present:'출석',Late:'지각',Absent:'결석',Excused:'사유결석',Rehab:'재활'};
  function attendanceView(){const dates=M.week(weekStart),ps=activePlayers(),training=o().trainingDays;return head('본업·주간 출석','본업 일정은 예정 불참입니다. 실제 출석은 확인한 뒤 기록해 주세요.',action('훈련 요일 설정','training-days')+btn('개별 훈련 기록','nav','training','data-view="training"'))+`<section class="panel"><div class="panelhead"><h2>${dates[0]} – ${dates[6]}</h2><div class="week-tools">${action('이전 주','week-prev')}${action('이번 주','week-current')}${action('다음 주','week-next')}</div></div><div class="table-scroll"><table class="attendance-table"><thead><tr><th>선수 / 본업</th>${dates.map((date,n)=>`<th>${days[n]}<br><span>${date.slice(5)}</span></th>`).join('')}</tr></thead><tbody>${ps.map(p=>`<tr><td><b>${esc(p.name)}</b><span class="subtext"><button class="link-btn" data-action="ops-job" data-id="${esc(p.id)}">${esc(p.dayJob||'본업 미입력')} · 일정 수정</button></span></td>${dates.map((date,n)=>{const a=M.attendance(state,p,date);if(!training.includes(n)&&!a.actual)return '<td class="day-off">—</td>';return `<td><select class="attendance-cell ${a.value==='busy'?'busy':a.value==='Present'||a.value==='Late'?'present':a.value==='Absent'?'absent':''}" data-ops-attendance="${esc(p.id)}" data-date="${date}" aria-label="${esc(p.name)} ${date} 출석"><option value="${a.value}">${attendanceNames[a.value]||esc(a.value)}${a.multiple?' (여러 기록)':''}</option>${Object.entries(attendanceNames).filter(([v])=>v!==a.value).map(([v,label])=>`<option value="${v}" ${(a.actual&&['planned','busy','default'].includes(v))||(date>M.localDay()&&['Present','Late','Absent','Excused','Rehab'].includes(v))?'disabled':''}>${label}</option>`).join('')}</select></td>`;}).join('')}</tr>`).join('')}</tbody><tfoot><tr><td>참가 예정 인원</td>${dates.map((date,n)=>`<td>${training.includes(n)?ps.filter(p=>!['busy','Absent','Excused','Rehab'].includes(M.attendance(state,p,date).value)).length+'명':'—'}</td>`).join('')}</tr></tfoot></table></div><div class="attendance-legend">${tag('회색: 본업 일정','muted')}${tag('파랑: 참가 예정','blue')}${tag('초록: 실제 출석·지각','green')}<span>말라위 날짜 기준 · 같은 날 훈련이 여러 번이면 개별 훈련 기록에서 수정해 주세요.</span></div></section>`;}
  function selectedFixture(){return state.fixtures.find(f=>f.id===disciplineFixture)||M.nextFixture(state)||state.fixtures.find(f=>!M.played(f))||state.fixtures[0];}
  function disciplineView(){const f=selectedFixture(),cid=f?M.competition(state,f):'',rule=o().discipline.rules[cid];return head('카드·출전 정지','대회별 규정과 경기 카드 기록으로 선택 경기의 출전 가능 여부를 계산합니다.',action('대회 규정 설정','rules')+btn('경기 카드 입력','new-record','plus','data-type="matchLogs"','primary'))+`<div class="panel filters"><label for="ops-discipline-fixture">확인할 경기</label><select id="ops-discipline-fixture" data-ops-fixture>${fixtureOptions(f?.id,false)}</select>${f?btn('이 경기 명단','ops-lineup','list',`data-id="${esc(f.id)}"`):''}</div><div class="spaced">${notice(rule?.enabled?`경고 ${rule.yellowThreshold}장 → ${rule.yellowBan}경기 · 퇴장 → ${rule.redBan}경기 정지. ${rule.effectiveDate}부터 적용. 완료된 같은 대회 경기에서 미출전이면 정지 1경기를 소화합니다.`:'대회 규정이 아직 설정되지 않았습니다. 실제 리그 규정을 확인해 입력한 뒤 계산을 켜 주세요.',true)}${rule?.enabled?`<p class="smallnote">규정 근거: ${esc(rule.source)} · 경고 2회 퇴장의 경고 ${rule.excludeSecondYellow?'누적 제외':'누적 포함'}. 기존 시즌 합계는 자동 합산하지 않으며 기초 누적에 직접 입력합니다.</p>`:''}${f&&!M.day(f.date)?notice('경기 날짜가 비어 있습니다. 날짜를 입력해야 카드 누적과 정지 소화를 계산할 수 있습니다.',true):''}</div><section class="panel"><div class="panelhead"><h2>선수별 카드 현황</h2><span class="tiny">선택 경기 직전 상태 · Suspended 선수 선택 제한</span></div>${table(['선수','경고 잔여 누적','퇴장 기록','출전 가능 여부','기초 누적'],activePlayers().map(p=>{const d=M.discipline(state,p.id,f);return `<tr><td><b>${esc(p.name)}</b>${p.dayJob?`<span class="subtext">${esc(p.dayJob)}</span>`:''}</td><td><span class="card-icon"></span>${d.yellow}</td><td><span class="card-icon red"></span>${d.red}</td><td>${tag(d.manual||d.remaining?'Suspended · '+d.reason:!d.enabled?'규정 확인 필요':!M.day(f?.date)?'날짜 확인 필요':'출전 정지 없음',d.manual||d.remaining?'danger':d.enabled?'green':'muted')}${d.missingDates?`<span class="subtext warning-text">날짜 없는 완료 경기 ${d.missingDates}개 제외</span>`:''}${d.violations.length?`<span class="subtext danger-text">정지 중 출전 기록 ${d.violations.length}건 확인 필요</span>`:''}</td><td>${action('기초 누적','discipline-opening',p.id)}</td></tr>`;}))}</section>`;}
  function weatherView(){return head('기상·훈련 공지','예보를 확인하고 현지 상황에 맞춰 공지를 직접 입력합니다.')+weatherPanel()+noticePanel()+`<section class="panel section-gap"><div class="panelhead"><h2>예보와 현지 확인</h2></div><div class="panelbody"><p>치주물루 좌표(12.020°S, 34.624°E)의 예보를 약 30분마다 갱신합니다. 한 시간 이상 지난 예보는 오래된 자료로 표시합니다.</p><p>풍향은 바람이 불어오는 방향입니다. Mwera와 배편 운항 상황은 현지에서 확인한 뒤 훈련 공지에 적어 주세요.</p><p>인터넷이 끊겨도 이미 받은 예보와 공지는 화면에 남습니다. 공지 변경은 연결이 돌아오면 공유 저장됩니다.</p></div></section>`;}
  Object.assign(operationsViews,{dashboard,finance:financeView,inventory:inventoryView,attendance:attendanceView,discipline:disciplineView,weather:weatherView});
  navItems.unshift(['CLUB OVERVIEW','dashboard','구단 대시보드','home']);
  navItems.splice(navItems.findIndex(n=>n[1]==='admin'),0,['CLUB OPERATIONS','finance','수입·지출 장부','chart'],['','inventory','장비·의무 물자','box'],['','attendance','본업·주간 출석','training'],['','discipline','카드·출전 정지','shield'],['','weather','기상·훈련 공지','calendar']);
  for(const n of navItems)titles[n[1]]=n[2];
  pFields.push(['dayJob','본업 (생업)','text']);
  recordConfigs.equipment.fields.splice(6,0,['consumed','사용·소모 누적 수량','number'],['targetStock','목표 보유 수량','number'],['unit','수량 단위','text']);
  Object.assign(recordConfigs.equipment.defaults,{consumed:0,targetStock:0,unit:'개'});
  const oldValidate=validData;validData=function(x){oldValidate(x);return M.validate(x);};
  equipmentAvailable=function(i){return M.available(state,i);};
  const oldName=namecell;namecell=function(p){const next=M.nextFixture(state),d=next?M.discipline(state,p.id,next):null,s=statsFor(p.id);return oldName(p)+(p.dayJob?`<span class="subtext">${tag(p.dayJob,'muted')}</span>`:'')+`<span class="subtext"><span class="card-icon"></span>${s.yellow} <span class="card-icon red"></span>${s.red}${d&&(d.manual||d.remaining)?' '+tag('Suspended','danger'):''}</span>`;};
  const oldLineup=renderLineup;renderLineup=function(){const html=oldLineup(),f=state.fixtures.find(f=>f.id===draftLineup?.fixtureId);return html.replace('<div class="lineup-grid">',`<div class="panel filters no-print"><label for="ops-lineup-player">선수 빠른 선택</label><select id="ops-lineup-player" data-ops-lineup><option value="">선수를 선택해 추가</option>${activePlayers().map(p=>{const d=M.discipline(state,p.id,f),blocked=d.manual||d.remaining>0,selected=draftLineup.entries.some(r=>r.playerId===p.id);return `<option value="${esc(p.id)}" ${blocked||selected?'disabled':''}>${esc(p.name)}${blocked?' · Suspended':''}${selected?' · 선택됨':''}</option>`;}).join('')}</select><span class="tiny">대회 규정에 따른 출전 제한 적용</span></div><div class="lineup-grid">`);};
  function lineupBadges(){if(view!=='lineup'||!draftLineup)return;const f=state.fixtures.find(f=>f.id===draftLineup.fixtureId);document.querySelectorAll('[data-lineup="select"]').forEach(input=>{const d=M.discipline(state,input.dataset.id,f);if(d.manual||d.remaining>0){input.disabled=!input.checked;const row=input.closest('.lineup-person');row?.classList.add('blocked');row?.querySelector('.grow')?.insertAdjacentHTML('beforeend',tag('Suspended · '+d.reason,'danger'));}});const blocked=draftLineup.entries.filter(r=>{const d=M.discipline(state,r.playerId,f);return d.manual||d.remaining>0;});if(blocked.length)document.querySelector('.lineup-summary')?.insertAdjacentHTML('afterend',`<div class="notice amber">출전 제한 선수가 있습니다. 왼쪽 체크를 해제해야 명단을 저장할 수 있습니다.</div>`);}
  const oldRender=render;render=function(){o();oldRender();lineupBadges();if(['dashboard','weather'].includes(view)&&(!CLOUD_SITE||canView()))refreshWeather(false);};
  function canView(){return typeof memberActive==='function'&&memberActive()&&cloud.ready;}
  try{const c=JSON.parse(localStorage.getItem(weatherKey)||'null');if(c&&typeof c.fetchedAt==='number'&&Date.now()-c.fetchedAt<86400000&&typeof c.time==='string')weatherData=c;}catch(e){}
  async function refreshWeather(force){if(weatherBusy||!force&&Date.now()-weatherAttempt<1800000)return;weatherAttempt=Date.now();weatherBusy=true;weatherError='';try{const u='https://api.open-meteo.com/v1/forecast?latitude=-12.020&longitude=34.624&current=wind_speed_10m,wind_direction_10m,wind_gusts_10m&daily=precipitation_probability_max&timezone=Africa%2FBlantyre&wind_speed_unit=ms&forecast_days=1';const response=await fetch(u,{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('날씨 연결 실패');const x=await response.json();if(!x.current||!x.daily||typeof x.current.time!=='string')throw Error('예보 형식 확인 필요');weatherData={time:x.current.time.replace('T',' '),wind:x.current.wind_speed_10m,direction:x.current.wind_direction_10m,gust:x.current.wind_gusts_10m,rain:x.daily.precipitation_probability_max[0],fetchedAt:Date.now()};try{localStorage.setItem(weatherKey,JSON.stringify(weatherData));}catch(e){}}catch(e){weatherError='연결 실패';}finally{weatherBusy=false;if(['dashboard','weather'].includes(view)&&(!CLOUD_SITE||canView())&&!document.querySelector('#dialog').open)render();}}
  setInterval(()=>{if(['dashboard','weather'].includes(view)&&(!CLOUD_SITE||canView()))refreshWeather(false);},60000);
  function openEditor(type,id){const f=o().finance,a=f.allowances.find(a=>a.id===id),t=f.transactions.find(t=>t.id===id),p=getPlayer(id);if(type==='opening')return editor('기초 잔액 설정',type,field('amount','기초 잔액 (MWK)','number',f.openingBalance,'required step="0.01"'));
    if(type==='transaction')return editor(id?'장부 기록 수정':'수입·지출 추가',type,field('date','기록일 (CAT)','date',t?.date||M.localDay(),'required')+select('type','구분',options([['income','수입'],['expense','지출']],t?.type||'expense'))+field('category','항목 (교통비, 식수·간식, 후원금 등)','text',t?.category||'','required maxlength="100"')+field('description','내용','text',t?.description||'','required maxlength="1000"')+field('amount','금액 (MWK)','number',t?.amount||'','required min="0.01" step="0.01"')+select('fixtureId','연결 경기',fixtureOptions(t?.fixtureId||'')),id);
    if(type==='allowance')return editor(id?'수당 수정':'선수 수당 등록',type,select('playerId','선수',playerOptions(a?.playerId))+field('date','발생일 (CAT)','date',a?.date||M.localDay(),'required')+field('reason','발생 사유 (훈련 참가, 승리 수당 등)','text',a?.reason||'','required maxlength="1000"')+field('amount','발생액 (MWK)','number',a?.amount||'','required min="0.01" step="0.01"')+select('fixtureId','연결 경기',fixtureOptions(a?.fixtureId||'')),id);
    if(type==='pay'&&a)return editor('수당 지급 기록',type,`<p class="form-wide">${esc(playerName(a.playerId))} · 미지급 ${money(M.outstanding(state,a))} MWK</p>`+field('date','지급일 (CAT)','date',M.localDay(),'required')+field('amount','지급액 (MWK)','number',M.outstanding(state,a),`required min="0.01" max="${M.outstanding(state,a)}" step="0.01"`),id);
    if(type==='stock'){const item=state.equipment.find(i=>i.id===id);if(!item)return;return editor('입고·사용 기록',type,`<p class="form-wide">${esc(item.name)} · 가용 재고 ${M.available(state,item)} ${esc(item.unit||'개')}</p>`+select('direction','구분',options([['in','입고'],['out','사용·소모']], 'in'))+field('quantity','수량','number',1,'required min="1" step="1"')+field('reason','사유','text','','required maxlength="1000"'),id);}
    if(type==='job'&&p)return editor('본업·요일 일정',type,field('job','본업 (생업)','text',p.dayJob||'','maxlength="100"')+daysField('busy',o().workSchedules[id]||[]),id);
    if(type==='training-days')return editor('정규 훈련 요일',type,daysField('trainingDays',o().trainingDays));
    if(type==='notice')return editor('훈련 공지 수정',type,field('title','공지 제목','text',o().notice.title,'required maxlength="200"')+`<div class="field form-wide"><label for="ops-body">공지 내용</label><textarea id="ops-body" name="body" maxlength="2000" required>${esc(o().notice.body)}</textarea></div><label class="fieldcheck"><input name="enabled" type="checkbox" ${o().notice.enabled?'checked':''}>공지 표시</label>`);
    if(type==='rules'){const cid=id||M.competition(state,selectedFixture()||{}),r=o().discipline.rules[cid]||{enabled:false,yellowThreshold:3,yellowBan:1,redBan:1,effectiveDate:M.localDay(),source:'',excludeSecondYellow:true};return editor('대회 징계 규정',type,select('competitionId','대회',options(state.competitions.map(c=>[c.id,c.name+' · '+c.season]),cid))+field('effectiveDate','계산 시작일 (기초 누적 기준일)','date',r.effectiveDate,'required')+field('yellowThreshold','누적 경고 기준','number',r.yellowThreshold,'required min="1" max="20" step="1"')+field('yellowBan','경고 누적 시 정지 경기 수','number',r.yellowBan,'required min="1" max="20" step="1"')+field('redBan','퇴장 시 정지 경기 수','number',r.redBan,'required min="1" max="20" step="1"')+field('source','확인한 규정 출처 / 담당자','text',r.source,'maxlength="1000"')+`<label class="fieldcheck form-wide"><input name="excludeSecondYellow" type="checkbox" ${r.excludeSecondYellow?'checked':''}>경고 2회 퇴장의 경고는 누적에서 제외</label><label class="fieldcheck form-wide"><input name="enabled" type="checkbox" ${r.enabled?'checked':''}>규정을 확인했고 자동 계산을 적용합니다.</label><p class="smallnote form-wide">3장·1경기는 입력 예시입니다. 실제 규정으로 수정해 주세요. 대회를 바꾸면 해당 대회의 저장된 규정이 열립니다.</p>`);}
    if(type==='discipline-opening'&&p){const cid=M.competition(state,selectedFixture()||{});if(!cid)throw Error('대회가 연결된 경기를 선택해 주세요.');const v=o().discipline.opening[cid+'|'+id]||{yellow:0,remaining:0};return editor('기초 누적 / 미소화 정지',type,`<input name="competitionId" type="hidden" value="${esc(cid)}"><p class="form-wide">${esc(p.name)} · ${esc(state.competitions.find(c=>c.id===cid)?.name)} · 규정의 계산 시작일 직전 상태</p>`+field('yellow','이미 받은 누적 경고 (기준 미만)','number',v.yellow,'required min="0" max="19" step="1"')+field('remaining','아직 소화하지 않은 정지 경기 수','number',v.remaining,'required min="0" max="20" step="1"'),id);}
  }
  function submit(form){const fd=new FormData(form),type=form.dataset.type,id=form.dataset.id,get=n=>String(fd.get(n)||'').trim(),num=n=>Number(fd.get(n)),date=()=>{const v=get('date');if(!M.day(v))throw Error('날짜를 확인해 주세요.');return v;},amount=()=>{const v=num('amount');if(!Number.isFinite(v)||M.money(v)<=0||Math.abs(v-M.money(v)/100)>1e-8)throw Error('금액은 소수점 두 자리 이하의 양수로 입력해 주세요.');return v;};change(({opening:'기초 잔액',transaction:'수입·지출',allowance:'선수 수당',pay:'수당 지급',stock:'입고·사용',job:'본업 일정','training-days':'훈련 요일',notice:'훈련 공지',rules:'대회 규정','discipline-opening':'기초 징계 기록'})[type]+'을(를) 저장했습니다.',()=>{const f=o().finance;if(type==='opening'){const v=num('amount');if(!Number.isFinite(v)||Math.abs(v-M.money(v)/100)>1e-8)throw Error('기초 잔액을 확인해 주세요.');f.openingBalance=v;}
    if(type==='transaction'){const old=f.transactions.find(t=>t.id===id);if(old?.allowanceId||old?.voided)throw Error('취소·수당 지급 기록은 직접 수정할 수 없습니다.');const r={...old,...stamp(),id:id||crypto.randomUUID(),date:date(),type:get('type'),category:get('category'),description:get('description'),amount:amount(),fixtureId:get('fixtureId'),voided:false};if(!r.category||!r.description)throw Error('항목과 내용을 입력해 주세요.');if(old)Object.assign(old,r);else f.transactions.push(r);}
    if(type==='allowance'){const old=f.allowances.find(a=>a.id===id),v=amount();if(old&&M.paid(state,id)>v)throw Error('발생액은 이미 지급한 금액 이상이어야 합니다.');if(!get('reason')||!getPlayer(get('playerId')))throw Error('선수와 발생 사유를 확인해 주세요.');if(old&&M.paid(state,id)&&old.playerId!==get('playerId'))throw Error('이미 지급한 수당의 선수는 변경할 수 없습니다.');const r={...old,...stamp(),id:id||crypto.randomUUID(),playerId:get('playerId'),date:date(),reason:get('reason'),amount:v,fixtureId:get('fixtureId'),voided:false};if(old)Object.assign(old,r);else f.allowances.push(r);}
    if(type==='pay')M.payment(state,id,{...stamp(),date:date(),amount:amount()});
    if(type==='stock')M.adjustStock(state,id,num('quantity')*(get('direction')==='out'?-1:1),{...stamp(),reason:get('reason')});
    if(type==='job'){getPlayer(id).dayJob=get('job');o().workSchedules[id]=fd.getAll('busy').map(Number);}
    if(type==='training-days')o().trainingDays=fd.getAll('trainingDays').map(Number);
    if(type==='notice')o().notice={title:get('title'),body:get('body'),enabled:fd.has('enabled')};
    if(type==='rules'){const cid=get('competitionId');if(!cid)throw Error('대회를 선택해 주세요.');if(fd.has('enabled')&&!get('source'))throw Error('확인한 규정 출처나 담당자를 적어 주세요.');o().discipline.rules[cid]={enabled:fd.has('enabled'),effectiveDate:get('effectiveDate'),yellowThreshold:num('yellowThreshold'),yellowBan:num('yellowBan'),redBan:num('redBan'),excludeSecondYellow:fd.has('excludeSecondYellow'),source:get('source')};}
    if(type==='discipline-opening'){const cid=get('competitionId'),r=o().discipline.rules[cid];if(r&&num('yellow')>=r.yellowThreshold)throw Error('기초 경고는 누적 기준 미만으로 입력하고 이미 발생한 정지는 별도로 입력해 주세요.');o().discipline.opening[cid+'|'+id]={yellow:num('yellow'),remaining:num('remaining')};}
  });closeDialog();}
  document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;if(el.dataset.action==='save-lineup'){const f=state.fixtures.find(f=>f.id===draftLineup?.fixtureId),blocked=draftLineup?.entries.filter(r=>{const d=M.discipline(state,r.playerId,f);return d.manual||d.remaining>0;});if(blocked?.length){e.preventDefault();e.stopImmediatePropagation();toast('출전 제한 선수를 명단에서 제외해 주세요.');}return;}if(!el.dataset.action.startsWith('ops-'))return;e.preventDefault();e.stopImmediatePropagation();const type=el.dataset.action.slice(4),id=el.dataset.id;try{if(!canEdit())throw Error('로그인 및 저장 상태를 확인해 주세요.');if(type==='weather-refresh'){refreshWeather(true);return;}if(type.startsWith('week-')){weekStart=type==='week-current'?M.week()[0]:M.shiftDay(weekStart,type==='week-prev'?-7:7);render();return;}if(type==='lineup'){lineupDraft(id);view='lineup';render();return;}if(type==='issues'){operationType='issues';subtab='issues';view='operations';render();return;}if(type==='void-transaction'){change('장부 기록을 취소했습니다.',()=>{const r=o().finance.transactions.find(r=>r.id===id);if(r)r.voided=true;});return;}if(type==='void-allowance'){change('수당 기록을 취소했습니다.',()=>{const a=o().finance.allowances.find(a=>a.id===id);if(M.paid(state,id))throw Error('지급 기록을 먼저 취소해 주세요.');if(a)a.voided=true;});return;}openEditor(type,id);}catch(err){toast(err.message);}},true);
  document.addEventListener('submit',e=>{if(e.target.id!=='ops-form')return;e.preventDefault();e.stopImmediatePropagation();try{submit(e.target);}catch(err){formError(err.message);}},true);
  document.addEventListener('change',e=>{const el=e.target;try{if(el.matches('[data-ops-fixture]')){disciplineFixture=el.value;render();}if(el.matches('[data-ops-notice]'))change('훈련 공지 표시 상태를 저장했습니다.',()=>{if(el.checked&&!o().notice.body.trim())throw Error('공지 내용을 먼저 입력해 주세요.');o().notice.enabled=el.checked;});if(el.matches('[data-ops-attendance]'))change('출석부를 저장했습니다.',()=>M.setAttendance(state,el.dataset.opsAttendance,el.dataset.date,el.value,crypto.randomUUID()));if(el.matches('[data-ops-lineup]')&&el.value){if(!canEdit())throw Error('저장 상태를 확인해 주세요.');const f=state.fixtures.find(f=>f.id===draftLineup?.fixtureId),d=M.discipline(state,el.value,f);if(d.manual||d.remaining)throw Error('출전 제한 선수입니다.');if(!draftLineup.entries.some(r=>r.playerId===el.value))draftLineup.entries.push({playerId:el.value,role:'Starter',captain:false,travel:false});render();}if(el.id==='ops-competitionId'&&el.closest('#ops-form')?.dataset.type==='rules')openEditor('rules',el.value);if(el.matches('[data-lineup="select"]')&&el.checked){const f=state.fixtures.find(f=>f.id===draftLineup?.fixtureId),d=M.discipline(state,el.dataset.id,f);if(d.manual||d.remaining){e.stopImmediatePropagation();render();throw Error('출전 제한 선수입니다.');}}}catch(err){toast(err.message);if(el.closest('#ops-form'))formError(err.message);else render();}},true);
  if(!CLOUD_SITE){view='dashboard';render();}
})();
