const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('path').join(__dirname,'../offline-media.js'),'utf8');
function fixture(uploadError=false,mismatch=false,switchAccount=false){let sent=0,flushed=0;const data='data:image/webp;base64,gA==',bundle={mediaQueue:[{path:'receipts/test/1234.webp',data}],mediaCache:[]},ctx=vm.createContext({Blob,Uint8Array,atob,console,Promise,document:{visibilityState:'visible',querySelector(){return null;}},setTimeout:(fn,t)=>{const x=setTimeout(fn,t);x.unref();return x;},clearTimeout,state:{players:[]},cloud:{ready:true},membership:{generation:1,user:{id:'one'},client:{storage:{from(){return {upload:async()=>{sent++;if(switchAccount){ctx.membership.generation++;ctx.membership.user={id:'two'};ctx.offlineSync.bundle={mediaQueue:[{path:'new-account'}]};}return {error:uploadError?Error('Lost reply'):null};},download:async()=>({data:new Blob([Uint8Array.of(mismatch?0x81:0x80)]),error:null})};}}}},offlineSync:{enabled:true,connected:true,busy:false,mediaBusy:false,bundle,working:{players:[]},persist:Promise.resolve()},save(){},syncNow:async()=>{flushed++;},persistSync:async()=>{},requireSyncSession:async()=>1,syncKey:()=>ctx.membership.user.id,refreshWorking(){},render(){},updateSaveStatus(){},cloudText:(_,en)=>en});vm.runInContext(source,ctx);return {ctx,stats:()=>({sent,flushed})};}
async function main(){let n=0;const check=x=>{assert.ok(x);n++;};let f=fixture();await vm.runInContext('syncNow()',f.ctx);check(f.stats().sent===1&&f.stats().flushed===1&&f.ctx.offlineSync.bundle.mediaQueue.length===0);
 f=fixture(true);await vm.runInContext('syncNow()',f.ctx);check(f.ctx.offlineSync.bundle.mediaQueue.length===0&&f.stats().flushed===1);
 f=fixture(true,true);await vm.runInContext('syncNow()',f.ctx);check(f.ctx.offlineSync.bundle.mediaQueue.length===1&&f.stats().flushed===0);
 check(await vm.runInContext('sameBlob(new Blob([Uint8Array.of(128)]),new Blob([Uint8Array.of(129)]))',f.ctx)===false);
 f=fixture(false,false,true);await vm.runInContext('syncNow()',f.ctx);check(f.ctx.offlineSync.bundle.mediaQueue[0].path==='new-account'&&f.stats().flushed===0);
 console.log('Media: '+n+' immutable replay, byte equality and account isolation checks passed');}
main().catch(e=>{console.error(e.stack);process.exit(1);});
